src/blockchain/p2p_blockchain/node.rs

Use the correct method.

---

docs/tutorial(PT-BR).md
readme.md
src/cli.rs
src/config_file.rs

Fix config file parse error and docs ortography

---

src/main.rs

This is useful for node solutions like umbrel and resplitz

read xpub from env var

---

src/blockchain/chain_state.rs
src/blockchain/chainparams.rs
src/blockchain/error.rs
src/blockchain/mod.rs
src/blockchain/p2p_blockchain/node.rs
src/blockchain/p2p_blockchain/peer.rs
src/cli.rs
src/electrum/electrum_protocol.rs
src/main.rs

if we add a new descriptor or address after we ibd, we need to go through all blocks looking for transactions we may be interested in

feat: Rescan

---

src/address_cache/kv_database.rs
src/address_cache/memory_database.rs
src/address_cache/mod.rs
src/electrum/electrum_protocol.rs
src/electrum/mod.rs

After we broadcast a transaction, this should reflect our address's balance

Update transaction view on broadcast

---

crates/floresta-wire/src/p2p_wire/address_man.rs
crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/node_context.rs
crates/floresta-wire/src/p2p_wire/peer.rs

Give floresta the ability to send addresses to our peers.

Send addresses

---

crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/node_interface.rs

This is similar to Bitcoin Core's addnode, but don't retry if the node is unreachable.

wire: Allow user to manually connect with a peer

---

crates/floresta-cli/src/main.rs
florestad/src/json_rpc/res.rs
florestad/src/json_rpc/server.rs
florestad/src/main.rs

The functionality exists, but wasn't reachable from RPC.

rpc: Create a method to manually connect with peers

---

crates/floresta-chain/src/pruned_utreexo/chain_state.rs
crates/floresta-wire/src/p2p_wire/node.rs

Since the proof isn't committed in the block, a malicious peer can make us invalidate a valid block by sending invalid proofs.

Don't invalidate block if proof is invalid

---

crates/floresta-chain/src/pruned_utreexo/chain_state.rs
crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/node_context.rs
crates/floresta-wire/src/p2p_wire/peer.rs

This is another attempt to make `chainstate` more robust about unexpected shutdowns.

make database more roboust

---

crates/floresta-chain/src/pruned_utreexo/chainparams.rs
crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta/examples/node.rs
florestad/src/cli.rs
florestad/src/main.rs

Closes #117
This option makes your node connect with a given peer, and only this peer. To test with a node running locally, use `--connect 127.0.0.1:8333`.

feat: -connect cli option

---

crates/floresta-chain/src/pruned_utreexo/chain_state.rs
crates/floresta-chain/src/pruned_utreexo/chainparams.rs
crates/floresta-chain/src/pruned_utreexo/mod.rs
crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
crates/floresta-common/src/lib.rs
crates/floresta-watch-only/src/lib.rs
crates/floresta-wire/src/lib.rs
crates/floresta-wire/src/p2p_wire/chain_selector.rs
crates/floresta-wire/src/p2p_wire/mod.rs
crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/node_context.rs
crates/floresta-wire/src/p2p_wire/peer.rs
crates/floresta-wire/src/p2p_wire/running_node.rs
crates/floresta/examples/node.rs
florestad/src/main.rs

This is a continuation of breaking #123 into multiple smaller changes. This PR will create a new module called `chain_selector` that will connect with multiple peers and try to find the most proof-of-work chain. We need to make this before anything, so we know what blocks to request and validate.

feature: chainselector

---

florestad/src/florestad.rs

OnceCell isn't `Sync`, we need for using `florestad` on uniffi

replace OnceCell with OnceLock

---

Dockerfile
readme.md

Declared version normalization

---

crates/floresta-wire/src/p2p_wire/chain_selector.rs

Modified the declaration of `agree` bool in `find_who_is_lying` function.

Bug fix: chain_selector

---

justfile

Add:
- fmt
- format 
- default that list commands
Fix: 
- specify "florestad" for `run` command.

Improve just file

---

README.md

it is `--assume-utreexo` not `--assumeutreexo`

readme: fix mention of --assume-utreexo option

---

README.md

Added command to install following prerequisites to README
- gcc 
- build-essential 
- pkg-config 
- libssl-dev

Added prerequisite to README

---

Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/utreexo_block_des.rs

Add fuzz target for `UtreexoBlock` deserialization.

fuzz: add `utreexo_block_des` target

---

.dockerignore
.github/workflows/rust.yml
Dockerfile
florestad/Cargo.toml
florestad/build.rs

This should fix a few problems with the dockerfile. It also adds a CI build for it, so we won't have breaking changes being merged in the future.
I think the nix build would also benefit from having a CI check (not implemented here)

Fix our dockerfile (once again)

---

tests/requirements.txt

Including the requests dependency in requirements.txt
@Davidson-Souza 
@brunoerg

fix:including requests on requirements.txt

---

crates/floresta-cli/src/lib.rs
florestad/src/florestad.rs
florestad/src/json_rpc/server.rs

As with #271, `floresta-cli` tests can fail sometimes due to port conflicts. This should fix it.
- Make the electrum addresses be assigned by the OS to avoid conflicts (args with port `0`)
- Similarly get an available port for the rpc server and the client, on the cli side
- Improve panic messages
Finally we change `RpcImpl::create` in order to fix the error:
> "Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context."
When `start_http` panics (e.g. when addr is already in use), its own runtime is dropped and we see this error, which hides the error that originated the panic. This is fixed by using our tokio runtime instead:
```rust
ServerBuilder::new(io)
.event_loop_executor(runtime_handle)
// Threads …
```

Fix cli tests and florestad panic messages

---

README.md

Added the Rust, docs.rs and license badges.

README: Add badges and fix headers

---

flake.lock
flake.nix

Now the pre-commit inside our nix dev shell matches what github actions do in what concern linting rust code.

feat: Specifying rustfmt and clippy to match github actions

---

crates/floresta-chain/src/pruned_utreexo/chainparams.rs
crates/floresta-chain/src/pruned_utreexo/mod.rs
crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
crates/floresta-cli/src/rpc.rs
crates/floresta-cli/src/rpc_types.rs
crates/floresta-common/src/spsc.rs
crates/floresta-compact-filters/src/flat_filters_store.rs
crates/floresta-compact-filters/src/lib.rs
crates/floresta-compact-filters/src/network_filters.rs
crates/floresta-electrum/src/electrum_protocol.rs
crates/floresta-watch-only/src/lib.rs
crates/floresta-wire/src/cli_wire/mod.rs
crates/floresta-wire/src/p2p_wire/chain_selector.rs
crates/floresta-wire/src/p2p_wire/error.rs
crates/floresta-wire/src/p2p_wire/node_context.rs
crates/floresta-wire/src/p2p_wire/running_node.rs
crates/floresta-wire/src/p2p_wire/sync_node.rs
crates/floresta-wire/src/p2p_wire/tests/test_data/block_hashes.txt
crates/floresta/src/lib.rs
florestad/docs/tutorial(PT-BR).md
florestad/src/cli.rs
florestad/src/florestad.rs
florestad/src/json_rpc/server.rs
florestad/src/zmq.rs
tests/example_test.py
tests/prepare.sh

Hopefully this fixes all spelling mistakes...

Fix all typos

---

crates/floresta-watch-only/src/lib.rs

Allows comment make more sense

Update lib.rs for floresta-watch-only-wallet

---

crates/floresta-wire/src/p2p_wire/sync_node.rs

This adds more documentation for `sync_node.rs` and fix a typo

[Docs] More docs to sync_node.rs

---

crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/peer.rs

Our current peer connection implementation has a potential issue with connection cleanup when peers disconnect. When we split the TcpStream and run the read half in a detached task, we rely entirely on the peer's proper shutdown behavior to terminate the connection. If the peer doesn't close their connection cleanly (which appears to be happening, causing `fin-wait2` states on Linux), the read task can remain active indefinitely, potentially leading to resource leaks like file descriptor exhaustion.
This PR implements a cancellation pattern for more reliable connection cleanup:
1. Added a oneshot channel to coordinate shutdown between the peer and its read task
2. When a peer initiates shutdown, it signals the read task through this channel
3. The read task now uses `tokio::select!` to …

Improving Peer Connection Shutdown Handling

---

pyproject.toml
tests/example_test.py
tests/floresta_cli_addnode.py
tests/floresta_cli_getblock.py
tests/floresta_cli_getblockchaininfo.py
tests/floresta_cli_getblockhash.py
tests/floresta_cli_getpeerinfo.py
tests/floresta_cli_getroots.py
tests/floresta_cli_stop.py
tests/restart.py
tests/test_framework/floresta_rpc.py
tests/test_framework/mock_rpc.py
tests/test_framework/test_framework.py

What is this PR for?
Added functional tests for floresta-cli's commands in a IBD context:
- [`getblockchaininfo`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#getblockchaininfo);
- [`getblockhash`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#getblockhash);
- [`getblock`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#getblock);
- [`getpeerinfo`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#getpeerinfo);
- [`stop`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#stop);
- [`addnode`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#addnode);
- [`getroots`](https://github.com/vinteumorg/Floresta/tree/master/crates/floresta-cli#getroots);
What is …

Added some functional tests for floresta-cli's commands in a IBD context

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE.md

This PR apply some idea from https://github.com/vinteumorg/Floresta/issues/348.
Various projects in bitcoin ecosystem uses some templates to help or format the ways the Issues/PRs are documented. With this in mind, it were:
* added issue template for bug report (with description, environment context, steps to reproduce) and another template for enhancement requests.
* Added a PR template with a brief description, an item selector for what was modified, as well as a checklist for the steps required before submitting the PR and a space for a description. As proof of concept, the submitted template is used in this PR.
These templates are a mix of templates used in [Krux](https://github.com/selfcustody/krux/tree/main/.github/ISSUE_TEMPLATE) as well …

Added issue/PR templates 

---

crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/peer.rs

Backports the bugfix for #294 added in #327 
Since after the tokio migration, we were getting a bug on linux where some connections would be on state `fin-wait2` forever. This would make florestad have too many connections open and use more CPU than needed (the tokio task wouldn't die). #327 fixed it by adding a cancellation logic to the task, allowing it to die in case of disconnection. As part of our new process, we'll get this backported to the releases we still support (in this case, 0.7.0).
This should be the last backport before `0.7.1`.

Backport 327 for 0.7.x

---

README.md

Added instructions to install `floresta-cli` to `PATH`
N/A

doc: add floresta-cli PATH installation command to README

---

README.md

README: Add floresta-docs link

---

Cargo.lock
crates/floresta-chain/Cargo.toml
crates/floresta-common/Cargo.toml
crates/floresta-compact-filters/Cargo.toml
crates/floresta-electrum/Cargo.toml
crates/floresta-watch-only/Cargo.toml
crates/floresta-wire/Cargo.toml
florestad/Cargo.toml

It is solving the issue #359 . Here  I have removed the dependencies that are not being used. 
I have run the test using cargo test --release
here is the test result 
It was solving this issue #359 
here is the test result

[Code-quality]: removed few dependencies that are not being used.

---

crates/floresta-chain/src/pruned_utreexo/consensus.rs

We weren't checking the coinbase output script limits, so added them to `verify_coinbase`. Also checking that the coinbase tx has a single input.
Plus minor style changes (I think the coinbase reward check is more readable now)

Check coinbase single input and output scripts

---

.github/workflows/benchmarks.yml

It is adding the benchmark workflow to CI. It is resolving the issue #266 
Here i have added the benchmark workflow in CI. i have taken reference from [fuzz.yml](https://github.com/vinteumorg/Floresta/blob/master/.github/workflows/fuzz.yml) . It is resolving the issue #266

CI : Added the benchmark workflow in CI

---

crates/floresta-chain/src/pruned_utreexo/chain_state.rs

Added docs for the `chain state` module.
- Addresses tracking issue #376 
- I added simple docs lacking. I tried to make it more atomic than the previous PR #401
- It appears the `ChainStateInner` however I was in doubt whether to add the docs or try to suppress it from showing in the docs. Should I suppress it?

Addresses #376 : added docs to chain-state

---

crates/floresta-chain/src/pruned_utreexo/chain_state.rs
crates/floresta-chain/src/pruned_utreexo/mod.rs
crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
crates/floresta-electrum/src/electrum_protocol.rs
crates/floresta-wire/src/cli_wire/mod.rs
crates/floresta-wire/src/p2p_wire/chain_selector.rs
crates/floresta-wire/src/p2p_wire/running_node.rs
crates/floresta-wire/src/p2p_wire/sync_node.rs
crates/floresta-wire/src/p2p_wire/tests/sync_node.rs
crates/floresta/examples/node.rs
florestad/src/json_rpc/blockchain.rs
florestad/src/json_rpc/server.rs
tests/floresta-cli/addnode-test.py

This PR renames the function `is_in_idb` to `is_in_ibd` and capitalizes `ibd` on comments.

fix: idb to ibd

---

crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs

Added missing docs for the Floresta Chain, specifically the Chain State Builder.
Most of the struct, the enum and the methods are self explaining. I added docs to keep it nice on cargo doc. Addresses #376

Docs chain state builder 

---

crates/floresta-wire/src/p2p_wire/running_node.rs
crates/floresta-wire/src/p2p_wire/sync_node.rs

Currently, if we are notified for a new block, we ask for headers and
then try to download the actual data. One problem may emerge if our
utreexo peers haven't seen the block (or are still processing it). We
may ask for a block that they don't have, making them take too long to
respond and get punished for it. Eventually, we will ban all our utreexo
peers, thanks to that.
This commit changes that logic to only attempt to download a new block
iff it gets announced by our utreexo peers; or if a while has passed
without anything new (in this case our utreexo peers may be withholding a block from us).
Also remove some duplicate code on `sync_node`.
Most of these bugs appears after leaving it running for a couple of days

running_node: don't ask for blocks until utreexo peers announce it 

---

crates/floresta-chain/src/pruned_utreexo/error.rs

Added missing descriptions of enums and structs regarding errors on floresta_chain.
Addresses #376 
I opted to not included comments for each field as each field is already self explaining.

Added simple docs to structs and enums of error

---

.github/PULL_REQUEST_TEMPLATE.md
justfile

I have added 3 pre-contributing check possibilities:
1. Using `just pcc`
2. Using a faster lint + test check
3. Checking CI on the forked repo
Also mentioned that signing commits is optional.
Finally made the `just lint-features` recipe format code (just like the cheaper `just lint`)

Improve the PR template checklist

---

crates/floresta-chain/src/pruned_utreexo/consensus.rs
crates/floresta-chain/src/pruned_utreexo/mod.rs
crates/floresta-compact-filters/src/lib.rs
crates/floresta-electrum/src/electrum_protocol.rs
florestad/src/florestad.rs
rust-toolchain.toml

Our current doc usage is missing a few links and gives several warnings. This PR aims to solve them before the next release `0.8.0`.
The warnings the rust doc throws are attached as file `warns.txt`.
[warns.txt](https://github.com/user-attachments/files/20140210/warns.txt)
This PR addresses issue #376 
* In cases where we don't already leak to the API a certain trait or struct, I opted for just highlighting it instead of linking it. An example is with the `std::error::Error`. It is not present at the scope. Before following this approach, I tried doing something specific to link just that case but I could not.
* For the `SyncNode` I opted leave its fix for the current open PR #375 
* For the `floresta-cli`naming conflict, this will only be solved when we up our rustc generating docs to …

[Fix] Fix doc warnings

---

Cargo.lock
crates/floresta-chain/src/pruned_utreexo/consensus.rs
crates/floresta-electrum/src/electrum_protocol.rs
crates/floresta-watch-only/src/lib.rs
crates/floresta-wire/src/p2p_wire/chain_selector.rs
crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/peer.rs
crates/floresta-wire/src/p2p_wire/running_node.rs
crates/floresta-wire/src/p2p_wire/sync_node.rs
crates/floresta-wire/src/p2p_wire/transport.rs
florestad/src/florestad.rs
florestad/src/json_rpc/server.rs

~Depends on #483~
This continues with the dependency bump, now it's the `log` crate. I've also had to fix some linting error introduced after the bump. Each subcrate is handled on separated commits.

Update the `log` crate

---

crates/floresta-common/src/lib.rs
crates/floresta-common/src/macros.rs

This PR adds missing docs from Floresta Common. It addresses #376 .
I added the reference to the electrum protocol to make it easier to search for. 

Added missing docs to Floresta Common

---

crates/floresta-chain/benches/chain_state_bench.rs

Both our `accept_header` and `connect_block` methods have early return cases for when we already have the header or have validated the block.
Hence the benches that used a single chainstate for all bencher iterations will use these early return cases. I have used the `iter_batched` method to set up the chainstate for every bencher iteration (excluded for the measurement), which makes them accurate now.
Also useful to avoid re-calling `connect_block` for already validated blocks, which we expect to make invalid after #488

Use fresh chainstates for each bencher iteration

---

crates/floresta-chain/src/lib.rs
crates/floresta-chain/src/pruned_utreexo/mod.rs
crates/floresta-wire/src/p2p_wire/chain_selector.rs
crates/floresta-wire/src/p2p_wire/node.rs
crates/floresta-wire/src/p2p_wire/running_node.rs
crates/floresta-wire/src/p2p_wire/sync_node.rs
florestad/src/json_rpc/server.rs

We rely on `BlockchainInterface` and `UpdatableChainState` traits to define how we expect the backend chain to be but it can became kind of repetitive mentioning every single trait. This is a try to mitigate this. 
Theres other ways to to different what i did here, that is, reducing trait bounds verbosity... Thoughts ?
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git commits](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html) and [GitHub's guide to signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/s …

Group chain traits

---

crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs

The methods that conceptually mutate the state (even if using raw pointers) should take `&mut self` to let the compiler enforce the ownership rules correctly. This way it will be harder for us to misuse the methods. We also get rid of the `#[allow(clippy::mut_from_ref)]`.
The only exception is `BlockIndex.set_index_for_hash` (because we pass a `&self` closure to it). This should be fine as we only use it inside `add_index_entry`.
Polished a bit the docstrings and fixed two conditional compilation warnings for Windows.

Use `&mut self` in FlatChainStore inner methods

---

florestad/src/florestad.rs
florestad/src/json_rpc/server.rs

* Add `info!` macro on json_rpc/server to log port;
* Specify `Electrum` word on electrum on `info!` macros.
This PR is for the first pre-task for #504 (logs for RPC) to complete #526;

Log RPC server info

---

florestad/src/florestad.rs

We can read the `ConfigFile` inside the wallet setup function, and also load the required data (xpubs, descriptors and addresses) inside a helper that replaces `get_both_vec`.

Florestad: refactor setup wallet data

---

crates/floresta-chain/src/pruned_utreexo/chain_state.rs

Closes #551
Before this commit, the re-index code would find the right place where we would work from, but not apply it to our chain. This could create spurious errors like #551.
This commit fixes that, and also improves how we handle accumulators on re-indexes. We now try to find our latest accumulator, move validation index there, then mark future blocks as `HeadersOnly` to not have problems with `BlockDoesntExtendTip`.
You can test this by killing floresta forcefully and starting again

fix: re-index didn't apply changes to chainstate

---

Cargo.lock
crates/floresta-chain/Cargo.toml
crates/floresta-cli/Cargo.toml
crates/floresta-common/Cargo.toml
crates/floresta-compact-filters/Cargo.toml
crates/floresta-electrum/Cargo.toml
crates/floresta-watch-only/Cargo.toml
crates/floresta-wire/Cargo.toml
crates/floresta/Cargo.toml
florestad/Cargo.toml
fuzz/Cargo.toml
metrics/Cargo.toml
tests/example/electrum-test.py

This PR bumps the version on all crates for the next release
I should've done this before branching out :joy:. I'll need to re-branch for `0.8.0`.

bump version for release

---

doc/running-tests.md

Add needed dependencies on documentation for running the functional tests.
This closes #574 

Update running tests

---

.github/PULL_REQUEST_TEMPLATE.md

I had this idea about suggesting that one could explain how the reviewer could objectively inspect the code and understand better where to pay more attention and effort besides providing another point of view about the issue itself and whats being done. 
What you guys think ?
Read the description to get some context
Judge if this really make any difference to understand whats being done here.
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git commits](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html) and [GitHub's guide to signing …

Merge Description and Notes, and adds new how-to-test in place

---

justfile

eafa9d1005cd76b5c370326d9a46380d71bf97b0 Introduced a just recipe that installs `typos-cli` on the hosts system to make a proper typo check.
Some systems may not have the cargo bin path included on the environment and this PR includes it.
Another change that i think that may be useful is to run the recipe latest as possible, since it requires more dependencies than the other recipes this should make the recipe do more work before it fails.
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git commits](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html) …

[FIX] Instantiate path with cargo bin path to find the binary

---

.github/PULL_REQUEST_TEMPLATE.md
tests/floresta-cli/getbestblockhash.py
tests/floresta-cli/getblockcount.py
tests/test_framework/electrum/client.py

#619 Introduced "new crates" and this PR adds them on the template
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git commits](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html) and [GitHub's guide to signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)).

[doc] reflect project repository changes on prtemplate
