vinteumorg/Floresta

config.toml.sample, src/blockchain/chain_state.rs, src/blockchain/chainparams.rs, src/blockchain/chainstore.rs, src/blockchain/cli_blockchain/mod.rs, src/blockchain/error.rs, src/blockchain/mod.rs, src/cli.rs, src/config_file.rs, src/main.rs
Implement reorganization logic for chain_state
=> Handle reorgs

src/main.rs
If we restart this program without removing already cached descriptors from the config file, it'll cache it again, effectively removing all
cached transactions.
This was due to is_cached comparing against descriptors, and we called it with xpubs, creating false negatives.
This commit fixes this by calling is_cached with the final descriptors
=> Fix a bug with descriptor caching

config.toml.sample, src/address_cache/mod.rs, src/cli.rs, src/error.rs, src/main.rs
Up to this point, we only cache xpubs. This adds the ability to handle individual addresses as well.
=> Cache individual addresses

Cargo.lock, Cargo.toml, config.toml.sample, docs/tutorial(PT-BR).md, src/cli.rs, src/error.rs, src/main.rs, src/wallet_input.rs
- Added support for output descriptors, including multisig
- Replaced xpub parsing with `slip132` crate because it was half-baked and messing up the correctness of the new tests
=> Added support for output descriptors

src/address_cache/kv_database.rs, src/address_cache/mod.rs, src/electrum/electrum_protocol.rs, src/error.rs
Fixes #28
Apparently, the way we currently handle transactions, if we have UTXO A for address X, and we have a transaction that both spends from A and creates a new UTXO B for an address Y that we control. We wouldn't have this transaction showing up in Y's history, only X's. 
Electrum can handle it because it parses transactions and checks if it changes some address we know, even if the server doesn't tell so. Sparrow follows exactly what the server tells, so in the example above, UTXO B wouldn't appear in the wallet.
This PR hardens how we handle UTXOs, making sure we don't have those collisions.
=> Fix sparrow incompatibility

src/address_cache/kv_database.rs, src/address_cache/mod.rs, src/wallet_input.rs
Until now, we only derived 100 addresses when we first get a descriptor, and never more. This commit allows generating more addresses after we receive 100 transactions.
=> Derive more addresses as we get transactions

src/blockchain/error.rs, src/blockchain/p2p_blockchain/peer.rs
We would send SendAddrV2 after verack, this is a violation of the handshake, and causes remote peer to hang on us
=> Fix a bug with prot 70016

src/blockchain/p2p_blockchain/node.rs
In some cases, we might ask for headers twice, downloading duplicated headers during ibd. This commit fixes it
=> Ask for headers only once

src/blockchain/p2p_blockchain/node.rs
While we don't leave ibd, this code wouldn't shutdown if requested
=> Fix a bug of hanging forever while on ibd

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs
Some code in chainstate doesn't require a knowledge of the current tip, and will be used in alternative implementations of chainstate, like partial_chainstate used in parallel sync. This commit is move-only.
=> Parallel sync 1/n: Refactor: Move stateless code to a new module

readme.md
the build creates `florestad`, not `floresta` as mentioned in the docs, this PR fixes the typo
=> Readme.md typo

Cargo.lock, crates/floresta-chain/Cargo.toml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-common/Cargo.toml, crates/floresta-common/src/lib.rs, crates/floresta-electrum/Cargo.toml, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/Cargo.toml, crates/floresta-wire/src/lib.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/stream_reader.rs, crates/floresta/Cargo.toml, crates/floresta/examples/chainstate-builder.rs, florestad/Cargo.toml, florestad/src/main.rs
Make some modules that are difficult to compile into wasm optional.
=> Improve support to wasm

crates/floresta-wire/src/p2p_wire/node.rs
In some previous iteration, the leaf_hashes wasn't being returned, and therefore, no proof verification was actually happening.
=> Fix: return leaf_hashes

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/mod.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/socks.rs, crates/floresta/examples/node.rs, florestad/src/cli.rs, florestad/src/main.rs
Up to now, peers would only use TcpSockets for connecting with others. But it would be nice if we can use other transports, like a SOCKS proxy or [Tor's Arti](https://tpo.pages.torproject.net/core/doc/rust/arti_client/index.html). This WIP refactors `Peer` to accept any transport.
=> Make peer generic over transport

crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/node.rs
Up to now, if we lost all utreexo peers, the node would stall and not accept any new blocks. With this commit, we retry to connect with peers that have succeeded in the past more often.
=> Bugfix: Don't hangup if we lose all utreexo peers

florestad/src/cli.rs, florestad/src/main.rs
Until now, to run florestad we need to provide a subcommand, but only one exists (run) and it is the default one. After this command you can call `florestad` without such subcommand and `run` will be assumed.
This commit also removes some unused code on main
=> florestad: allow running without subcommand

Cargo.lock, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-common/Cargo.toml, crates/floresta-common/src/lib.rs, crates/floresta-common/src/spsc.rs, crates/floresta-electrum/src/electrum_protocol.rs
Currently, if a module wants to get blocks as they are accepted, they should pass in a channel to `chainstate` and pool this channel for new blocks. That works fine for services (i.e: modules that have a loop watching stuff happening) but some modules might not be services, like the filters backend introduced in #89. This PR changes the subscription logic to "pass in an Arc-ed object that implements `BlockConsumer`".
It also implements a `Sync + Send + 'static` channel that depends solely on `alloc`, and implements `BlockConsumer`. The `std` `mspc` channel receiver isn't `Send`, making it tricky to use it across `await` points; using channels from `async-std::channel` adds the function coloring problem to the notification mechanism, which is undesirable. Moreover, we only need to send …
=> WIP: Rework block notification

Cargo.lock, florestad/Cargo.toml, florestad/src/cli.rs, florestad/src/main.rs, florestad/src/zmq.rs
The Zero Message Queue is a lightweight protocol for inter process communication. It is used on Bitcoin Core to allow external softwares to be notified when some events happen (e.g. new block is accepted). This PR adds a simple PUSH/PULL socket that pushes a new block, and it's height over ZMQ every time a new block is accepted by chainstate.
=> feature: push blocks over zmq

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-wire/src/p2p_wire/node.rs
If all our utreexo connections are lost, and we take too long to recover, we might download blocks out-of-order and mess our acc up. This commit makes sure blocks are accepted in only in order.
=> Bugfix: recover from utreexo nodes hangup

.github/workflows/functional.yml, tests/example_test.py, tests/prepare.sh, tests/requirements.txt, tests/run_tests.py, tests/test_framework/README.md, tests/test_framework/bitcoin.py, tests/test_framework/floresta_rpc.py, tests/test_framework/key.py, tests/test_framework/secp256k1.py, tests/test_framework/test_framework.py, tests/test_framework/utreexod.py
This is another attempt to bring our functional tests to life. Now that the crate separation project is finished-ish, we can make functional tests to make sure `florestad` behaves as it should.
The goal here is to add more building blocks for the test framework, rather than actually adding tests.
=> Bring our functional tests to life

crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta/examples/node.rs, florestad/src/main.rs
Banning a peer at the first time they misbehave (e.g. timeout a request) might be overaggressive, and lead to us being depleted of utreexo peers.
This commit adds a banscore system. Every time a peer misbehaves we increase that score. If it reaches a certain value, we ban them.
=> don't ban on the first violation

crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs
For versioning purposes, we want to prepend the preimage with a tag. There's more efficient ways to do this but that requires modifying rust-bitcoin and this is just the most straightforward way to implement tagged hashes.
=> Implement tagged hashes for the leafhashes

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs, crates/floresta-common/src/lib.rs, crates/floresta-wire/src/p2p_wire/node.rs
Because #123 became really long and difficult to review, this PR is the first of a series that will break that changes into multple self-contained ones. This one mostly finalizes the `PartialChainState` logic, by allowing the creation of one from the actual `ChainState` and implementing the relevant traits.
=> create partial chainstates from a full chainstate

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs
A few suggested changes:
1. Better readability for `reindex_chain`
2. It seems that `maybe_reorg` is saving the branch tip with its parent height, so I add 1
3. `accept_header` should perhaps return if there's a database error
4. `verify_block_transactions` should just return `Ok(())`, instead of `Ok(true)`, since any other outcome is returned as `Err`
I also found an issue in `validate_block`:
We check if `block.header.prev_blockhash != prev_block.block_hash()`. But `prev_block` is fetched with `header.prev_blockhash`, so this check always passes! I don't know what is the desired behavior here.
=> Improve reindex_chain readability and small fixes

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs
I believe the other `BlockValidationErrors` in `verify_block_transactions` should be returned as they are, and use `InvalidTx` only to return a specific transaction validation error.
=> Return when there's a tx validation error

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs, crates/floresta/examples/chainstate-builder.rs, crates/floresta/examples/node.rs, florestad/src/main.rs
I have added the `AssumeValidArg` enum to make the disabled and hardcoded options explicit, as discussed in #126.
Also I have changed `verify_script` to check whether there's an assume-valid hash, and if so also check if the block is in the best chain (now, if it is forked we won't assume the scripts). We no longer use the `assume_valid` field height, as we directly fetch the disk header (in order to verify the state of the block).
Updated the two examples. In florestad/src/main.rs I add a temporary conversion to `AssumeValidArg`, in next changes we could modify slightly the Command enum such that the assume-valid argument has this type.
=> Add AssumeValidArg enum and correct verify_script

readme.md
the README has the incorrect command for adding florestad to the path, previously it was -
```bash
cargo install --path .
```
which resulted into the below error : 
> found a virtual manifest at '{path}/Floresta/Cargo.toml' instead of a package manifest
the new command is - 
```
cargo install --path ./florestad
```
this makes sure that we are installing path from the correct directory and this command is run after executing the `cargo build --release --bin florestad`
=> fixed adding florestad to path while building

florestad/src/config_file.rs
* Fixes issue #138 
* Removed the fields which are not used currently in florestad/src/config_file.rs which were causing the linting errors.
=> CI:fixes the linting error

crates/floresta-electrum/src/electrum_protocol.rs
Modified the handle_message  function of electrum_protocol for handling batch requests
closes #107
=> feature: batch request for electrum

.gitignore, Cargo.lock, florestad/Cargo.toml, florestad/src/cli.rs, florestad/src/main.rs
"I've implemented a new feature to log messages to a file. 
Since the previous logger, pretty_env_logger, couldn't log into a file, 
I've removed it. Instead, I've integrated "Fern' as the new logger. This allows us to log messages to stdout and a log file."
closes #135
=> feature: log to file

Cargo.lock, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta/Cargo.toml, crates/floresta/examples/node.rs, florestad/Cargo.toml, florestad/src/cli.rs, florestad/src/florestad.rs, florestad/src/json_rpc/server.rs, florestad/src/lib.rs, florestad/src/main.rs, florestad/src/slip132.rs, tests/test_framework/test_framework.py
This commit introduces a lib.rs for florestad. With this change, other softwares can spawn a florestad process and run on the background.
=> florestad: Add lib.rs

crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-watch-only/src/lib.rs
Those endpoints aren't part of the upstream yet, but they improve the UX
of floresta and other index-less electrum servers like EPS.
Floresta doesn't keep a full index of all addresses that ever received
sats, as this would take multiple GBs. As a result, users can't ask for
arbitrary addresses on-demand.
However, with BIP157 client-side filters we can rescan for and address
in a relatively efficient way. However, by BIP158 compact block
filters, we can't use the Electrum out-of-the-box because they index the
scriptpubkey, not script hashes like electrum does. With this endpoint,
rather than sending the scripthash, we send the actual scriptpubkey.
With the script, we can use BIP158 filters to find transactions
belonging to a given address.
The endpoints are just all endpoints from …
=> electrum: new experimental electrum endpoints

crates/floresta-wire/src/p2p_wire/chain_selector.rs
Extended the parameters of `request_headers` function, by mentioning the `peer_id` of the peer to which the `GetHeaders` req is being sent to. 
Previously when `request_headers` function was called it was always sending req to `node.sync_peer`.
=> Potential bug fix in floresta-wire/chain_selector.rs

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
See #162 for context.
After a reading at `crates/floresta-chain/`, based on commenting and codebase...
Floresta, what concern the validation of Transactions, has
* In block transaction structure validation. ( Verifies if has, at least, one transaction per block, if has coinbase, etc...)
* Script validation.
* PrevOut validation. (If has a valid PrevOut).
So, based on [Core `validation.cpp`](https://github.com/bitcoin/bitcoin/blob/ecd23656db174adef61d3bd753d02698c3528192/src/validation.cpp#L4003) and [@Davidson-Souza comment on #162 ](https://github.com/Davidson-Souza/Floresta/issues/162#issuecomment-2124092038)
The lacking Rules are:
<details><summary>Values validation.</summary>
<p>
- Output value is equal or less than total input (Implemented, just needs tests)
</p>
<p>
- none value is …
=> Transaction Consensus Rules

crates/floresta-wire/src/p2p_wire/node.rs
If we have 10 non-utreexo peers and we lose our last utreexo connection, we'll stop downloading blocks. With this commit, even if we have 10 peers, we allow one extra connection if we need a utreexo peer.
=> fix: force utreexo peers

crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
When we ban a peer, we also have to remove the inflight requests related to that peer and send those to a random_peer.
=> bug fix: remove inflights of banned peers

crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/src/p2p_wire/mod.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, florestad/src/cli.rs, florestad/src/florestad.rs, florestad/src/main.rs
if we download all filters on mainnet, that will take ~11GB of disk
space. But it's unlikely that users will have UTXOs going all the
way back to the first few blocks. This commit introduces a new option
to only download filters after a given height.
If the provided value is negative, we compute an offset from the
current height
=> cfilters: let user pick an initial height

crates/floresta-wire/src/p2p_wire/mod.rs, crates/floresta-wire/src/p2p_wire/tests/mod.rs, crates/floresta-wire/src/p2p_wire/tests/sync_node.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
Simulated a peer to take in requests for the sync-node instance. Filled the chain-state with some block-headers prior block validation and then send the appropriate responses to the node.
=> Functional tests for floresta-wire/sync-node

florestad/src/florestad.rs
Instead of:
```
loaded compact filters store at height: Ok(123)
```
print the value itself:
```
loaded compact filters store at height: 123
```
=> minor improvement when printing height

crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
If some time has passed and we didn't see a tip update, we open a new extra connection. We do this to prevent the case where our subnet is somehow partitioned from the global network and we don't get new blocks. The problem with the current code is that it doesn't destroy another connection and always keep the new one. If let running for enough time, florestad will create too many connections and take a lot of CPU.
This commit fixes this by adding a new rule for extra peers; we only keep them if they have blocks we didn't have. If they don't have any unknown blocks, we disconnect. If they do, we disconnect one peer, based on how fast they announce a new block to us. Faster peers are preferable instead of slow ones.
=> Only keep extra peers if they give us a new block

crates/floresta-compact-filters/src/flat_filters_store.rs, crates/floresta-compact-filters/src/lib.rs, crates/floresta-compact-filters/src/network_filters.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs
Right now, if we receive filters out of order, we'll consider that a misbehaving. But due to some weird connectivity or even how the remote node processes things, we may get those in a random order. This commit fixes that by holding the filters we've got in a BTree and only processing it after all the previous filters already got processed.
=> Wire: handle block filters out-of-order

Cargo.lock, Cargo.toml, README.md, fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/local_address_str.rs
This is a very simple fuzz target but might be the start of a journey :) 
Since there is no fuzzing in this project, I added `cargo-fuzz` into it.
To run:
```
cargo +nightly fuzz run local_address_str
```
=> fuzz: add target for `LocalAddress` from string

florestad/src/json_rpc/server.rs
Some RPCs timeout if we try to make them while on IBD, and this gets the RPC server stuck forever. This commit forbids running them during IBD, and return an error.
=> rpc: don't try to run some rpcs if in ibd

Cargo.lock, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-watch-only/Cargo.toml, crates/floresta-watch-only/src/lib.rs, florestad/src/florestad.rs, florestad/src/json_rpc/server.rs
This would allow us to make the Electrum Server optional, in case you want to use the json-rpc or even use the wallet directly.
=> wallet: make it work without the Electrum Server

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, florestad/src/cli.rs, florestad/src/florestad.rs, florestad/src/main.rs
Explicit rescan is when we download and scan all blocks in a given range. This is not only inefficient, but the current code is buggy and would need some improvements.
Since we now have support for block filters, there's no point in keeping this alive.
=> chain/wire: remove the explicit rescan code

Cargo.lock, crates/floresta-chain/Cargo.toml, crates/floresta-electrum/Cargo.toml, crates/floresta-watch-only/Cargo.toml, crates/floresta-wire/Cargo.toml, florestad/Cargo.toml
Use cargo udep to find unused dependencies and remove them. Some are only used on tests, in this case they got moved to dev-dependency.
=> deps: remove unused deps

crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/seeds/mainnet_seeds.json
Some early commit introduced a malformed mainnet seed, this will cause a fresh build of floresta to crash. This PR removes it, and creates a test that will catch the problem if it ever happens again.
=> Fix local seeds

crates/floresta-chain/src/pruned_utreexo/chain_state.rs
In #234 the `maybe_reindex` `FullyValid` match case was removed, so calling it for a `FullyValid` header doesn't do anything. Changed `maybe_reindex` to use an `if let` instead.
=> Remove unused maybe_reindex

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, florestad/src/florestad.rs
I think the natural location for them is in chainparams, alongside `assume-utreexo` hashes. Removed the `_value` suffix for both getters.
In florestad I brought into scope the trait needed for calling `subscribe` at line 380, and also changed a &String to &str.
=> Move assume-valid hashes to chainparams

README.md, tests/requirements.txt
README.md were pointing to inexistence file https://github.com/vinteumorg/Floresta/blob/master/florestad/config.toml 
Fixing to ./config.toml.sample instead 
@Davidson-Souza
=> Fixing path to config.toml.sample

Cargo.lock, Cargo.toml, crates/floresta-common/src/lib.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
Up to now we used a fork of rust-bitcoin for utreexo stuff, but we moved many of them to floresta itself. This commit almost removes completely the usage of the modified code, making it almost possible to use the mainline rust-bitcoin
=> reduce dependency on forked rust-bitcoin

Cargo.lock, crates/floresta-chain/Cargo.toml, crates/floresta-common/Cargo.toml, crates/floresta-common/src/lib.rs
I have tried to make `floresta-common` be able to compile without the standard library.
1. Added the missing `no-std` feature in `Cargo.toml`, together with a default `std` feature.
2. Added the missing `core2` and `hashbrown` dependencies (used in the `no-std` prelude).
3. `sha2`, `miniscript` and `bitcoin` default features disabled to avoid importing `std-lib`, although our new `std` feature enables it.
4. Also added a new `descriptors-no-std` feature to use them without the `std-lib`.
It should be able to compile without `std-lib` by running `cargo build --no-default-features --features no-std`, but we get an error with the current fork of the `bitcoin` crate. Concretely at `bitcoin/src/consensus/encode.rs`:
```rust
impl_vec!(UtreexoBlock);
impl_vec!(CompactLeafData);
``` …
=> No_std support for floresta-common

README.md, build.nix, flake.nix
Fixes https://github.com/vinteumorg/Floresta/issues/253.
The problem with our nix was rust override.
After thinking a bit, its far from normal to a rust developer use more than a version of rust, so i delegated rust version control directly to rustup since it does the job better while doing development(nix-shell). just was added as a dev tool too
The build.nix had some overrides too, so i updated some meta-data and forced nix to pull rust version directly from rust-toolchain.toml. Now its easier to change dependencies.
=> Feat: refactor nix files.

README.md
Added section for mac users and an "disclosure" on the possible warning/error message due to ssl certificates not being loaded correctly.
=> Update read me 

florestad/src/florestad.rs
On running the node, it displays an ERROR if the SSL certificates are not loaded correctly. Changed it to a WARN.
=> changed from `error` to `warn` message on logging the ssl cert load

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-electrum/src/lib.rs, crates/floresta-watch-only/src/lib.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
- Removed unneeded `#[allow(clippy::significant_drop_in_scrutinee)]` and `#[allow(clippy::await_holding_lock)]` in `chain_state.rs`
- Directly initialize `params` in `electrum_protocol.rs`
- Added `#[allow(clippy::too_many_arguments)]` for two functions
- A few more trivial changes
Mainly the remaining warnings are about feature flags to be implemented.
=> Fix clippy warnings

florestad/src/json_rpc/server.rs
Before this commit, if we called `loaddescriptor`, it wouldn't cache the addresses, and our wallet wouldn't find any transactions, even if we get a filters hit.
After this, we do cache the first 100 addresses before rescanning
=> rpc: cache addresses on loaddescriptor

README.md, crates/floresta-electrum/src/electrum_protocol.rs
I noticed sometimes the `floresta-electrum` tests don't pass (e.g. like in my previous PR checks).
Since each test previously used a randomly chosen port within the range 18443 - 19442, along with `port + 1`, tests would occasionally fail with an "Address already in use" error due to port conflicts.
The port selection is now set to `0`, allowing the OS to automatically assign an available port. This change should eliminate this error.
=> Fix electrum tests

crates/floresta-chain/Cargo.toml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-cli/Cargo.toml, crates/floresta-cli/src/lib.rs, crates/floresta-cli/src/rpc_types.rs, crates/floresta-common/Cargo.toml, crates/floresta-common/src/lib.rs, crates/floresta-watch-only/Cargo.toml, crates/floresta/Cargo.toml, florestad/Cargo.toml, florestad/src/florestad.rs, florestad/src/main.rs, florestad/src/zmq.rs
*Floresta-chain*
- The `bitcoin/bitcoinconsensus` feature was still needed for the `verify_with_flags` method on `Transaction`
- `BlockHeader` is used without the feature
*Floresta-cli*
- Made `jsonrpc` not optional, as it is needed for the main function to actually run a client
- Changed the way we get the florestad path
*Floresta-common*
- Remove `no-std` feature to avoid the mutually exclusive features, as advised in https://doc.rust-lang.org/cargo/reference/features.html#mutually-exclusive-features. If `std` feature is not set, we are in `no_std`
*Floresta-watch-only*
- Update the common dependency accordingly
*Florestad*
- Make `json-rpc` feature use `compact-filters` as the Rpc trait methods require compact filters
- Missing conditional compilation
Since we don't have yet a CI check …
=> Fix compile errors for all feature combinations

contrib/test_features.sh, justfile
Created a `.sh` script using the [cargo-hack](https://crates.io/crates/cargo-hack) tool in order to easily test all feature combinations. This is done in `--release` mode to reduce the size of the compiled artifacts.
The script is located in a new `contrib` directory (same approach followed by `rust-bitcoin` crates). This will be useful for CI as well.
=> Add test-features recipe to justfile

.github/workflows/rust.yml, crates/floresta-cli/src/lib.rs
Closes #241 
This PR builds on top of #276. This is a significant improvement for floresta as we will now check that no feature setup is broken and all tests pass across feature sets.
The `cargo` caches used for the `cross-testing` job are now smaller due to `release` builds (600MB macOS, 780MB Linux, 720MB Windows). While CI runtime has increased, it's still reasonable: 8–9 minutes for macOS and Linux, and 19 minutes for Windows (the slowest GitHub Actions runner).
The first CI run after merging into `master` will take longer due to cache rebuilding, but subsequent runs will align with the ~19 minutes.
- Remove caching from the `lint` job as it is less critical for these quick checks (now takes ~1 min).
- Introduce `CACHE_VERSION` to the cache key, updated bi-weekly.
- Use only release …
=> CI: Test all feature combinations

crates/floresta-wire/src/p2p_wire/running_node.rs
If some peer sent us a block without proof to our `RunningNode` we would try to unwrap the `udata` and panic. This commit actually handles the case and remove the panic
=> Remove an externally reachable unwrap

florestad/src/cli.rs, florestad/src/florestad.rs
While reviewing the files in the `florestad` folder to better understand the project, I noticed and fixed some minor typos in the docstrings. These changes aim to improve readability and maintain consistency in the documentation.
- Corrected minor typos in the docstrings within `florestad/src`.
I hope these edits are helpful! If for any reason this change isn’t aligned with the project’s current priorities, please let me know, and I’m happy to adjust or close the PR.
=> docs: correct typos in docstrings within florestad/src

Cargo.lock, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/mod.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/tests/sync_node.rs, crates/floresta/examples/node.rs, florestad/Cargo.toml, florestad/src/florestad.rs
Closes #284
Now you can pass a hostname (i.e.: localhost, node, vps) for addresses in configs like `rpc-address` and `electrum-address`. The format is <hostname>[:port].
One question is whether we should just pick the default one or to crash if we can't resolve the name. I'm leaning towards crashing, at least for the binding addresses.
=> feat: allow hostnames where we take addresses

crates/floresta-wire/src/p2p_wire/node.rs
https://github.com/vinteumorg/Floresta/pull/286#issuecomment-2499116642
As mentioned in this comment the hostanames features was relying on a feature gate on windows (only on tests). Instead, i made the `resolve_connect_host` function to always specificate localhost while setting the ipv4.... This change was tested and developed on a native windows system.
This change adds the following behavior to hostnames: "When no ip is specificated, floresta will try to use 127.0.0.1"
=> Fix on allow-hostnames

justfile
As shown by lucas here https://github.com/vinteumorg/Floresta/issues/295#issuecomment-2515337540 , #295 could be fixed aligning the versions of `cargo build` and the declared version in "rust-toolchain.toml". 
~~So i matched the version inside the justfile.~~
~~I know this changes looks strange inside the justfile and possibly will be another data to maintain if we update our MSRV.
But we need it, its the only way to certify such a external thing from our project.~~
Nope, not needed.
closes #295
=> fix: specify version on just commands to avoid incorrect versions being used

Cargo.lock, build.nix, crates/floresta-chain/Cargo.toml, crates/floresta-cli/Cargo.toml, crates/floresta-common/Cargo.toml, crates/floresta-compact-filters/Cargo.toml, crates/floresta-electrum/Cargo.toml, crates/floresta-watch-only/Cargo.toml, crates/floresta-wire/Cargo.toml, crates/floresta/Cargo.toml, florestad/Cargo.toml
As discussed in #287, this makes the release for v0.7.0. We now need to test the code in this version and make sure it works and is stable enough.
=> Prepare for v0.7.0

crates/floresta-cli/README.md, crates/floresta-cli/src/main.rs, crates/floresta-cli/src/rpc.rs, crates/floresta-cli/src/rpc_types.rs
This PR resolves an issue where `floresta-cli` was sending a `getrawtransaction` command while `florestad` expected a `gettransaction` command.  
The solution updates `floresta-cli` to use the `gettransaction` command, aligning it with the Bitcoin reference implementation as outlined in the [Bitcoin RPC documentation](https://developer.bitcoin.org/reference/rpc/gettransaction.html) for the `gettransaction` command:  
> Get detailed information about **in-wallet** transaction `<txid>`  
1. Updated the `Methods::GetRawTransaction` enum variant to `Methods::GetTransaction` in `main.rs`.
2. Renamed the corresponding command attribute from `getrawtransaction` to `gettransaction`.
3. Fixed the `FlorestaRPC` implementation to call the correct method (`gettransaction`) in `rpc.rs`.
4. Updated the …
=> Fix mismatch between `floresta-cli` command and `florestad` server

crates/floresta-cli/src/jsonrpc_client.rs, crates/floresta-cli/src/main.rs
Added comments to the main function and helper functions to explain the purpose and functionality of each part of the RPC client code. Should help improve code readability and maintainability.
=> Add comments to explain RPC client code

.dockerignore, .gitignore, contrib/clean_data.sh, crates/floresta-chain/benches/chain_state_bench.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-cli/src/lib.rs, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-watch-only/src/kv_database.rs, crates/floresta-wire/src/p2p_wire/tests/sync_node.rs, crates/floresta/examples/chainstate-builder.rs, crates/floresta/examples/node.rs, justfile
The `data` directory was used for ChainStore databases generated during testing. It has been renamed to `tmp-db` to explicitly signal it's a temporary log (we are using another `tests/data` directory for python tests but this one is non-generated and permanent).
A new shell script and just recipe have been added in order to delete all test-generated data. It prompts the user for confirmation with the found `tmp` and `tmp-db` directories.
=> Add clean-data recipe, rename data/ dir to tmp-db/

Cargo.lock, Cargo.toml, Dockerfile, README.md, crates/floresta-chain/Cargo.toml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, docker-compose.yml, florestad/Cargo.toml, florestad/src/florestad.rs, metrics/Cargo.toml, metrics/grafana/datasource.yml, metrics/prometheus/prometheus.yml, metrics/src/lib.rs
Closes #166 .
This PR adds support for [Prometheus](https://prometheus.io/), while giving an example of its integration with [Grafana](https://grafana.com/) as well.
- Adds new (optional) cargo project named `metrics` that holds information about the Prometheus metrics and that can be used in a singleton way;
- Adds `docker-compose.yml` file to examplify how to deploy floresta+prometheus+grafana infra;
- Adds two example metrics: system memory used (GB) and current block height.
Example of added metrics in Grafana:
> Be sure to have [Docker Compose](https://docs.docker.com/compose/)
Run `docker-compose up -d --build`, wait for it to start all services and then go to http://localhost:3000/, where you can log into Grafana using the given credentials found in the `docker-compose.yml` file. …
=> Add prometheus support

README.md, justfile
Most of the times when contributing code to the repo I find myself only realising that I missed some linting, formatting or checking after the Github Actions job is triggered and fails.
This adds a new `just` recipe called `pre-contributing` that aims to help contributors to run a single command before opening a PR, making sure that everything is working correctly and nothing is missing.
=> Add pre-contributing just recipe

README.md, justfile
Renamed to `pcc` (pre-commit check). Formatting is already done as part of the `lint` recipe.
=> Check features in the pre-commit recipe

Cargo.lock, florestad/Cargo.toml, florestad/src/florestad.rs, florestad/src/json_rpc/res.rs, florestad/src/json_rpc/server.rs, tests/test_framework/floresta_rpc.py
Since we already use axum for the metrics crate, and the currently used crate is unmaintained. This commit re-implements the json-rpc using axum.
Once nice side effect is that if we ever want to use another encode or websockets, axum already supports that.
This commit also improves error handling, creating more specific errors and returning them when appropriated.
=> json-rpc: use axum for server

crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, crates/floresta-wire/src/p2p_wire/tests/sync_node.rs, crates/floresta/examples/node.rs
While searching a way to implement `MTP`, i got myself a lot of the times with the `UtreexoNode` declaration aside my readings trough *florestad`s internals* just because
```Rust
pub struct UtreexoNode<T, Chain>(
NodeCommon<Chain>,
T
)
```
The generic trait declaration is inverted and the fields had no name, usually being called as `self.0` or `self.1` which is not so intuitive to look at.
>UtreexoNode Signature is `UtreexoNode<T,Chain>` but to make chain operations in (e.g. access NodeCommon) you had to use `self.0`
IMO is better to always name internal fields if they're being accessed from outside the struct and not only from internal methods for that structure
=> [Fix] Add names for UtreexoNode fields 

crates/floresta-chain/src/pruned_utreexo/chainparams.rs
This commit adds a new mainnet dns seed that lets us fetch utreexo peers
=> dnsseed: add a new seed that supports utreexo

crates/floresta-cli/src/lib.rs, crates/floresta-cli/src/main.rs, crates/floresta-cli/src/rpc.rs, crates/floresta-cli/src/rpc_types.rs, florestad/src/json_rpc/blockchain.rs, florestad/src/json_rpc/mod.rs, florestad/src/json_rpc/res.rs, florestad/src/json_rpc/server.rs
Depends on #322 
This is the first step towards a core-compatible(ish) json rpc. This should help other applications to integrate with `florestad` without requiring any additional work.
List of things achieved here:
Things that we'll need to build next (not done here):
=> Blockchain rpcs

crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
Proposing these changes as the BlockRules PR was closed.
- Added a few `?` when needed.
- Corrected the non-taproot max script size to 10,000 bytes. `validate_script_size` now takes a `taproot_spend` bool.
Then also fix some error return cases:
- Check if the first tx is coinbase and return `FirstTxIsNotCoinbase` if it is not. `verify_coinbase` was previously only called if `transaction.is_coinbase() && n == 0` and the not coinbase case was not handled.
- Previous `get_out_value` returned error when output had 0 sats value, but this is valid under the consensus rules. Removed it.
- `consume_utxos` changed to `get_utxo`: the utxos are already consumed by the `verify_with_flags` method, since it takes a `utxos.remove(outpoint)` closure.
=> Return tx validation errors, fix max script size

Cargo.lock, crates/floresta-cli/src/lib.rs, crates/floresta-cli/src/main.rs, crates/floresta-cli/src/rpc.rs, crates/floresta-cli/src/rpc_types.rs, florestad/Cargo.toml, florestad/src/florestad.rs, florestad/src/json_rpc/control.rs, florestad/src/json_rpc/mod.rs, florestad/src/json_rpc/res.rs, florestad/src/json_rpc/server.rs, florestad/src/main.rs
This PR implements the following RPCs:
`getmeminfo`: Returns information about our memory usage
`getrpcinfo`: Stats about our jsonrpc server
`uptime`: How long our daemon has been running, in seconds
It also updates `stop` to make it return a string "florestad stopping" just like core's "Bitcoin Core stopping".
I'm not implementing `help` and `logging` from the control category
`help` is already implemented in `floresta-cli` by `clap`
`logging` requires a level of logs filtering we don't really have
=> jsonrpc: add control commands

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
This is more suitable as `Block` has a method that directly computes the weight (accounting for the header and coinbase, which we didn't).
In `validate_block_no_acc` I added a few `.into()`. Renamed `FirstTxIs/n/NotCoinbase` to `FirstTxIsNotCoinbase`
=> Move block weight check to `validate_block_no_acc`

.github/workflows/functional.yml, .gitignore, flake.nix, justfile, tests/prepare.sh, tests/run.sh, tests/test_framework/test_framework.py
This piece of changes tries to automate our python tests inside our justfile.
`test-int` now just executes `"poetry run poe tests"` command defined in `pyproject.toml` and in `run_tests.py`.
the old `test-int` is renamed to `test-wkspc` to match better the internal command and to give space for the integration tests with python.
new command `test-int-nix` uses a nix-shell to setup every python crap, downloading and compiling utreexod and florestad, run the tests and exits
=> Python tests in justfile with nix

florestad/src/florestad.rs, pyproject.toml, tests/floresta_cli_getmemoryinfo.py, tests/floresta_cli_getrpcinfo.py, tests/floresta_cli_uptime.py, tests/test_framework/floresta_rpc.py, tests/test_framework/test_framework.py
Added functional tests for floresta-cli commands:
* `getmemoryinfo`
* `getrpcinfo` 
* `uptime`
=> Added functional tests for getmemoryinfo, getrpcinfo, uptime

crates/floresta-chain/src/pruned_utreexo/chainparams.rs
`seed.bitcoin.luisschwab.com` implements these filters:
- **x9**: NODE_NETWORK | NODE_WITNESS
- **x49**: NODE_NETWORK | NODE_WITNESS | NODE_COMPACT_FILTERS
- **x1000009**: NODE_NETWORK | NODE_WITNESS | NODE_UTREEXO
- **x1000049**: NODE_NETWORK | NODE_WITNESS | NODE_COMPACT_FILTERS | NODE_UTREEXO
=> chore: add new utreexo seed [seed.bitcoin.luisschwab.com]

crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-wire/src/p2p_wire/address_man.rs
This PR removes the unresponsive `seed.bitcoin.jonasschnelli.ch` and `dnsseed.bitcoin.dashjr.org` DNS seeds, and also adds better logging on the peer discovery phase.
=> fix,log: remove unresponsive peers, better DNS logging

crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-wire/src/p2p_wire/address_man.rs
This PR backports two dns seed related PRs to versions 0.7.x.
Due to some peers in `mainnet-seeds.json` going offline, anyone running `0.7.0` or lower won't be able to connect. They will just stay stuck forever. #343 and #344 solves this on `master`, but this commit backports to our latest stable release, so we can make a new minor release fixing the problem.
These are the exact same changes made by #343 and #344.
=> Backport of #343 #344

CONTRIBUTING.md, README.md
This PR fixes issue  https://github.com/vinteumorg/Floresta/issues/354
The README.md and CONTRIBUTING.md need a little fix in some links. Both either point to wrong or invalid resources.
In the introductory section of README.md, the pre-built binaries link was pointing to version `v0.4.0` and the current version is `0.7.0`.
It would be better to have a dynamic pointing to releases using github's `/releases/latest` endpoint.
The maintainer PGP key link pointee to a invalid link (blog.dlsouzadot.lol/assets/pgp.asc give a 404 HTTP error).
This PR simple changes `pgp.asc` to `gpg.asc` in the refered link in both README.md and CONTRIBUTING.md.
=> Fix release and PGP maintainer links in README and CONTRIBUTING

.github/workflows/fuzz.yml
This PR introduces automated fuzz testing to the CI/CD pipeline. Every pull request or push to the master branch will trigger all the fuzz tests located in the floresta-fuzz directory.
This PR addresses the addition of fuzz testing to the CI/CD pipeline, as outlined in issue #350. The goal is to enhance the robustness and reliability of the codebase by automatically running fuzz tests on every PR and push to the master branch.
- Why Fuzz Testing? 
Fuzz testing is a powerful technique to uncover edge cases and potential vulnerabilities by providing random, invalid, or unexpected inputs to the system. Integrating it into the CI/CD pipeline ensures that these tests are run consistently, catching issues early in the development process.
- Implementation Details: 
The fuzz tests are located in …
=> add fuzz testing to ci-cd

florestad/src/florestad.rs, florestad/src/json_rpc/server.rs
This PR handles errors when trying to bind to already already bound resources (datadir, RPC and Electrum ports).
It logs an error! and then exits via `std::process::exit(1)`:
```
$ ./target/debug/florestad
[2025-02-04 09:59:04 ERROR florestad::florestad] Cannot obtain a lock on data directory $HOME/.floresta/. Floresta is probably already running.
```
If using another datadir:
```
$ ./target/debug/florestad --data-dir=data
[2025-02-04 09:59:13 INFO florestad::florestad] Starting server
[2025-02-04 09:59:13 WARN florestad::florestad] Failed to load SSL certificates, ignoring SSL
[2025-02-04 09:59:13 ERROR florestad::florestad] Failed to bind to address 0.0.0.0:50001. There is probably an Electrum server already running.
```
Two tests fail when running `cargo test`, but they are also …
=> fix(florestad): don't panic if a lock cannot be obtained to the datadir, RPC and Electrum ports

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Made the PR template cleaner: the description section should be enough (`Which aspect of floresta its being addresed?` is redundant).
Added CONTRIBUTING.md to checklist section
Fixed typos on CONTIBUTING.md
PS: this PR is using the new template
=> doc: make template more concise, add ref to CONTRIBUTING.md on template

crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, florestad/src/slip132.rs
This PR fixed issue #361 part 2 fixing serde clippy warning.
The purpose of PR is to fix clippy warning related to serde in slip132 and improving code quality along with applying fix to empty line.
As per recommendation the serde import can be simplified, and serde is always available so we can have a direct way by importing. 
Simplifying serde in [slip132.rs]
Fix the clippy warning - 
```consider parenthesizing your expression: `0x40000002 | (1 << 24)`  ```
```empty line after doc comment```
=> code quality- Fixing serde clippy warning

Cargo.lock, crates/floresta-chain/Cargo.toml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs, crates/floresta-electrum/Cargo.toml, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/Cargo.toml, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/mempool.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/tests/sync_node.rs, crates/floresta/Cargo.toml, crates/floresta/examples/node.rs, florestad/Cargo.toml, florestad/src/florestad.rs
We can now check proofs for unconfirmed transactions, cache them and create blocks. However, we won't ask for peers to send transactions for now.
=> Feat: Create some very basic mempool stuff

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/tests/sync_node.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
This PR is realted to #358 . Fixing and removing remaining code simplification clippy warnings.
Fixing and removing remaing code simplification clippy warnings.
No clippy warning can be seen now
Created type aliase ```type PeerData = (HeaderList, BlockHashMap, BlockDataMap);```  for ```very complex type used``` warning.
=> code quality:Fix code simplification clippy warnings

Cargo.lock, crates/floresta-common/src/lib.rs, crates/floresta-wire/Cargo.toml, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, florestad/Cargo.toml, metrics/src/lib.rs
Add a few new metrics endpoints for prometheus: number of peers, average time to validate a block and a histogram for peer latency
Each commit fully implements one metric
=> More metrics

crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs
I have created a `tx_err` macro to succinctly build a `TransactionError`. This has the benefit of skipping the `BlockValidationErrors::` enum prefix when specifying the error, and flexibly taking a third argument for the inner variant value.
Instead of:
```rust
return Err(TransactionError {
txid: transaction.compute_txid(),
error: BlockValidationErrors::NotEnoughMoney,
}
.into());
```
We do:
```rust
return Err(tx_err!(txid, NotEnoughMoney))?;
```
The validation methods now directly return `TransactionError` and use a lazily evaluated closure to compute the `txid` if there's an error.
The `pub mod error` line is now before `pub mod consensus` to make the macro available. Finally changed the "Invalid coinbase txid" error message to "Invalid Coinbase PrevOut".
This reduces the error mapping …
=> Refactor `consensus.rs` error mapping

.github/workflows/rust.yml, crates/floresta-watch-only/src/merkle.rs, crates/floresta-wire/src/p2p_wire/node_context.rs
I have fixed the remaining clippy warnings, and now CI fails if there are any. If new nightly clippy issues are added over time our CI will fail (unrelated to the specific PR) but I guess it is fine as it notifies us the new recommendations.
=> Make CI fail on clippy warnings

crates/floresta-electrum/src/electrum_protocol.rs
=> Docs: alignment typo

flake.nix
I noticed that the developer tools are not being added to the default developer shell. I solved this by adding them to `nativeBuildInputs`, but I am relatively new to nix and am not sure this is the best pattern.
=> build: ensure dev tools available on PATH

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs, crates/floresta-wire/src/p2p_wire/mempool.rs, crates/floresta-wire/src/p2p_wire/running_node.rs
Since `BitcoinNodeHash` implements `From<bitcoin_hashes::sha256::Hash>`, we can directly apply `Into::into`. Then for str conversions we can use `parse` instead, and map the arrays directly.
Finally in `chain_state.rs` and `partial_chain.rs` I simplify `BlockchainError::BlockValidation` conversions with `?`.
=> Simplify hash and error conversions

crates/floresta-chain/src/pruned_utreexo/consensus.rs
A output's script may be bigger than 10k bytes, it just can't be spent. We incorrectly check the script pubkey size when it gets created, causing floresta to break out of consensus if such an output is mined.
Fixes #393
Tests for this will be integrated on #387
=> consensus: fix a problem with script sizes

pyproject.toml, tests/floresta_cli_getblockheader.py, tests/test_framework/floresta_rpc.py
Add a test for #252
This PR add a structure to test calls of `getblockheader` in `tests/test_framework/floresta_rpc.py`, a simple test in `tests/floresta_cli_getblockheader.py` and a helper in pyproject.toml as `florestacli-getblockheader-test`.
This simple test just call the `getblockheader` with the hash of regtest's genesis block and expect, among some data, a prev_blockhash full of zeros.
It's important to note that this PR can be closely related to PR [#391](https://github.com/vinteumorg/Floresta/pull/391).
=> Added test for getblockheader JSONRPC call

crates/floresta-chain/src/pruned_utreexo/consensus.rs
We forgot removing this check (coinbase output scripts, like any other, can be >10KB).
=> Remove output size checks from `verify_coinbase`

crates/floresta-chain/src/lib.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs
I have created the `bhash` macro, short for block hash, that enforces a compile time check on the literal (must be 64 hex digits).
It uses the pattern `const _: () = ...;`, where the right side is evaluated at compile time. All the `bhash!(literals)` will be checked at compile time, even if they are not accessed at runtime (see https://doc.rust-lang.org/reference/items/constant-items.html#evaluation).
In other words, code that contains invalid literals won't compile (while currently it would compile and the program would panic at runtime only if the value is used). Also an IDE with cargo check lints will now display the error immediately.
You can verify that this works, you can try to mess with any hash values and then try to compile: it won't.
```bash
error[E0080]: evaluation of constant …
```
=> Validate hash literals at compile time

Cargo.lock, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/Cargo.toml, crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/mod.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/socks.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs, crates/floresta-wire/src/p2p_wire/transport.rs, florestad/src/cli.rs, florestad/src/florestad.rs, florestad/src/main.rs
The new `transport` module wraps up the V1 and V2 p2p protocols so that the rest of the app doesn't have to care, but this lead to a few refactors and open questions.
* Shifted the use of `RawNetworkMessage` to `NetworkMessage`. RawNetworkMessage is essentially a V1 message (bit of a misnomer) whereas NetworkMessage is agnostic. Considering the transport module handles V1 or V2, the rest of the app doesn't care and can just use NetworkMessage.
* The read and write enum types exposed by the `transport` module require some more explicit type bounds throughout the rest of the app. These aren't new requirements, they were just implicit before.
* Pushed the TCP and SOCKS5 connection logic into the new transport module so that it can handle retries at that level. I believe this will make future …
=> Add v2 p2p support (BIP324)

crates/floresta-chain/src/lib.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs
I added missing docs to Floresta Chain crate, prunned utreexo module and its submodules to help on #376 .
I avoided adding the docs for the structs inside each submodule to make it easier for review.
=> added docs to prunned_utreexo module and its submodules

crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/node_interface.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
This commit changes how we select peers to create random connections with unknown addresses, so if we don't have enough good peers, we can try getting finding some instead of just getting stuck.
This commit also opens non-utreexo connections if we don't have any addresses, so we can find some and at least learn about the best chan of headers.
NA
=> wire: improve connection logic

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs
If a tx spends an oversized output, the error originates in this tx, not in the previous one (which is valid). So the `TransactionError` txid should, in my opinion, be from the current tx, i.e. the invalid one.
Then some minor simplification:
- Using `deserialize_hex`, rather than `Vec::from_hex` + `deserialize`
- Creating the `txout` and `txin` macros
- Refactoring `test_spending_script_too_big`
=> Use current txid for script errors, simplify tests

crates/floresta-chain/src/lib.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainparams.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs, crates/floresta-common/src/lib.rs, crates/floresta-common/src/macros.rs, crates/floresta-wire/src/p2p_wire/mempool.rs, crates/floresta-wire/src/p2p_wire/tests/utils.rs
Created a new `macros` module at `floresta-common`. Moved here the `bhash` and `impl_error_from` macros.
Then implemented the `nodehash` macro, following a similar approach as `bhash`. We now validate the block hashes and node hashes literals at compile time everywhere.
=> Validate utreexo node hashes at compile time

crates/floresta-chain/src/pruned_utreexo/udata.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
In order to test `process_proof` without having a `ChainState` with the previous blocks, we make the function take a generic `F: Fn(u32) -> Result<BlockHash, E>`.
Then for tests we pass a closure with the required hashes, and elsewhere we use `|h| self.chain.get_block_hash(h)`, instead of passing the whole `&self.chain`.
We also move the `udata.proof` conversion into the `From` trait implementation. Finally reduce nesting in the `process_proof` body.
The behavior of `process_proof` should be **unchanged**, I only refactored the `BatchProof` conversion to `Proof`, renamed `inputs` to `utxos`, `hashes` to `del_hashes`, and reduced nesting by calling `continue`.
=> Add `process_proof` test, make it more modular

.github/workflows/fuzz.yml
Closes #415 
The current CI test boostraps the fuzzer every time we run the CI due to it not using any corpus. That reduces the usefulness of running fuzz on CI. Instead of just using the fuzzer like this, we should use some corpus that already have a decent coverage and will stress our code in a satisfactory way.
This commit uses the corpus data provided by the floresta-qa-assets repository. It contains corpus data generated over months of continuous fuzzing.
=> CI: use corpus for fuzzing

crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/node_interface.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, crates/floresta/examples/node.rs, florestad/src/json_rpc/blockchain.rs, florestad/src/json_rpc/res.rs, florestad/src/json_rpc/server.rs
This commit changes the node interface to send a notification, instead of waiting for the node to check on it.
This simplifies some of the code and solves the problem with the handle being unresponsive if the node is under a lot of load.
=> wire: refactor the handle to use notifications

florestad/src/cli.rs
#215 flipped the assume-utreexo flag but not its description. 
didnt searched futher about other mentions of assume-utreexo that can have its meaning flipped to be in agreement of #215 changes.
=> Fix: description of assume utreexo was backwards

.github/workflows/rust.yml, contrib/feature_matrix.sh, crates/floresta-common/src/lib.rs, florestad/src/florestad.rs, justfile
Renamed `test_features.sh` to `feature_matrix.sh`, which now can execute two actions for all features: clippy or test.
The script can be run as:
`./contrib/feature_matrix.sh {clippy|test} [cargo_arg]`
Similar to the `test-features` just recipe, I have added a `lint-features` one.
You can easily verify that this works by adding any unused import that is not compiled by default. Then run `just lint-features '-- -D warnings'` (to trigger an error, which we do in CI)
=> CI: Check clippy on all feature combinations

Cargo.lock, README.md, florestad/Cargo.toml, florestad/src/cli.rs, florestad/src/error.rs, florestad/src/florestad.rs, florestad/src/main.rs
Fix #423
This flag, when passed to florestad, will create a ssl folder in `<data-dir>` and `<data-dir>/ssl/key.pem` and a self-signed `<data-dir>/ssl/cert.pem`. This self-signed certificate can be a option to those users that do not have certificates with a trusted chain. It's import to note that the private-key isn't encrypted.
More specifically, this commit add:
* a flag --gen-selfsigned-cert on CLI;
* some enums elements on error.rs
* a generate_selfsigned_certificate on florestad.rs;
* a new step on florestad::start method before creating the TLS-enabled electrum server.
This PR is a followup of #421
=> Added --gen-selfsigned-cert flag

crates/floresta-chain/benches/chain_state_bench.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
I have added the same `UtxoData` struct from PR #300, but with an additional `is_coinbase` flag. We get the flag from the utreexo leaf header code, just like the utxo creation height. The utxo creation unix time is not computed nor used anywhere (covered at #300).
The `Consensus::verify_transaction` now checks the spent coinbase tx outputs maturity. `ChainParams` has a constant for the maturity period but it's always 100 regardless of the network.
Most of this diff is refactoring `TxOut` to `UtxoData` in functions. I'm generally not using a `UtxoMap` type alias in order to keep the map types explicit on a first look.
This PR should should make #300 more focused on the timelock checks and unix time computation, and less so on refactors.
=> Create `UtxoData` and check coinbase maturity

crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs
On a clean `datadir` florestad raises an error about `anchors.json` that was actually a expected behavior.
fix #438
=> Fix: raise warn instead of error if anchors arent made yet

tests/example/example-test.py, tests/floresta-cli/addnode-test.py, tests/floresta-cli/getblock-test.py, tests/floresta-cli/getblockchaininfo-test.py, tests/floresta-cli/getblockhash-test.py, tests/floresta-cli/getblockheader-test.py, tests/floresta-cli/getmemoryinfo-test.py, tests/floresta-cli/getpeerinfo-test.py, tests/floresta-cli/getroots-test.py, tests/floresta-cli/getrpcinfo-test.py, tests/floresta-cli/stop-test.py, tests/floresta-cli/uptime-test.py, tests/florestad/restart-test.py, tests/florestad/ssl-fail-test.py, tests/florestad/ssl-test.py, tests/test_framework/floresta_rpc.py, tests/test_framework/test_framework.py
Fix #426 
Added a pipeline for assertions, where a failure of a condition start a node's shutdown procedure. The pipeline can be used with these methods:
* assertTrue for boolean condition;
* assertEqual for expected general condition;
* assertIn for expected item in a list;
* assertMatch for expected strings in a given regex pattern;
* assertRaises for expected exceptions.
The pipeline was applied in these suites:
* Added assertion pipeline to example suite;
* Added assertion pipeline to floresta-cli suite;
* Added assertion pipeline to florestad suite.
This PR depends on #431 to work without false positives.
=> Fix non stop florestad process in functional tests

crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/node.rs
This PR builds on #439 to also removes the warning when trying to persist Utreexo peers. Now the `NoUtreexoPeersAvailable` variant is used instead.
I took the liberty of modifying the  `try_and_warn!` macro and the error strings, as I think the output looks cleaner now.
```
$ florestad
[2025-04-11 18:36:02 WARN florestad::florestad] Could not read config file, ignoring it
[2025-04-11 18:36:02 INFO florestad::florestad] Wallet setup completed!
[2025-04-11 18:36:02 INFO florestad::florestad] Loading blockchain database
[2025-04-11 18:36:02 INFO florestad::florestad] Loaded compact filters store at height: 0
[2025-04-11 18:36:02 INFO florestad::florestad] Starting server
[2025-04-11 18:36:02 WARN florestad::florestad] Failed to load SSL certificates: Error while opening PKCS#8 certificate …
```
=> fix(wire): don't error if we don't have any utreexo peers to save

doc/running-tests.md, tests/floresta-cli/addnode-test.py, tests/floresta-cli/getmemoryinfo-test.py, tests/floresta-cli/getrpcinfo-test.py, tests/floresta-cli/uptime-test.py, tests/florestad/restart-test.py, tests/prepare.sh, tests/run.sh, tests/run_tests.py, tests/test_framework/test_framework.py
Right now the functional tests uses `~/.floresta` as datadir and builds utreexod on $PWD. That kills the insulation idea behind the tempdir we are using. This commit fixes this by building utreexod inside the tempdir/build and using tempdir/data as datadir
Then, I've implemented a logic to allow using any version of `utreexod`. In the future, we can run `floresta` against different versions of `utreexod` and `bitcoind`.
=> functional-tests: allow using different versions of utreexod

crates/floresta-chain/src/pruned_utreexo/chainstore.rs
I added docs for the Chain Store module inside prunned utreexo. It was lacking documentation.
Addresses #376 
I got a little confused with the usage of the prefix underscore on `_store` and with the `index` field. I did not understand it usage. I believe there could be an improvement in these descriptions.
=> Added docs for chain store module

crates/floresta-chain/src/pruned_utreexo/chainparams.rs
I added a doc strings to a few pertinent functions inside the chain-params. 
Addresses #376 
I refactored docstrings from line comments to better addresses the documentation. Only one function is exposed in the API but I also added docstrings to others.
=> added docs for chain-params.rs (#376)

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-cli/src/lib.rs, crates/floresta-cli/src/main.rs, crates/floresta-compact-filters/src/flat_filters_store.rs, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-watch-only/src/kv_database.rs, crates/floresta-watch-only/src/lib.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta/examples/node.rs, crates/floresta/examples/watch-only.rs, florestad/build.rs, florestad/src/error.rs, florestad/src/florestad.rs, florestad/src/json_rpc/res.rs
Fix #458
Rust nightly added a new linting that warns interpolation styles. This was noted when trying to run CI on #452 .
=> Fix rust lint warnings

crates/floresta-chain/src/pruned_utreexo/consensus.rs
#457 introduced a change that broke a new lint for string interpolation. For some reason, it didn't break on the PR itself, but did break after merge. This commit fixes it and should get CI green again.
=> chain: fix a CI break with linting

crates/floresta-chain/src/pruned_utreexo/udata.rs
This PR aims to add missing docs for submodule `proof_util`.  
It addresses #376 
I have attached screenshots for the differences on the docs but notice I also added comments on private functions.
Was:
Is:
=> Added docs for proof_util module 

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chain_state_builder.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta/examples/chainstate-builder.rs
Relates to #463. This is a first step on hardening error handling.
Previously we were using `unwrap` for things like chainstore operations and `Option` values unwrapping in the `ChainStateBuilder` methods.
I have replaced all unwraps in the file with proper error handling. Added the new `IncompleteTip` and `Database` error variants. Polished a bit the comments.
Also instead of implementing `From` ChainStateBuilder for Chainstate I implement `TryFrom` (it's fallible, failing if the chainstore and chain params are not set).
=> Handle ChainStateBuilder errors, avoid unwraps

crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-chain/src/pruned_utreexo/udata.rs
Relates to #463. A couple of replacements of `unwrap` for `expect` with proper messages.
In partial_chain.rs `get_validation_flags` now takes the hash directly from the caller, avoiding the `unwrap` (exactly as we do for `get_validation_flags` [in chain_state.rs](https://github.com/vinteumorg/Floresta/blob/master/crates/floresta-chain/src/pruned_utreexo/chain_state.rs#L167)).
In `get_leaf_hashes` (udata.rs) we instead take the TxOut directly. We also avoid computing the txid twice by passing it.
The only remaining `unwraps` in `floresta-chain` are in `chain_state.rs`. We can then remove them (with a bit of error handling) and enforce they are not re-introduced.
=> Small refactors to remove unwraps

.github/workflows/functional.yml, doc/running-tests.md, tests/prepare.sh
Add:
A name for the CI functional workflow
new check_installed function
build flag to force florestad building
fix:
the florestad symlink now its directly from the actual dir, as a absolute path. cargo
build will update the linked binary too.
echoing the directory at the end so one just see the dir if the
script ran fine
try to fix https://github.com/vinteumorg/Floresta/pull/461#discussion_r2066316318
- [] I ran `just lint`
- [] I ran `cargo test`
=> [FIX] prepare.sh now override pre-built binaires

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-common/src/macros.rs, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-watch-only/src/merkle.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/mempool.rs
We have a couple of `assert!(result.is_ok())` and `assert!(result.is_err())` in our tests. These are very readable but whenever they fail they don't debug the `Result` value. We have recently seen this lack of debugging in some electrum tests CI fails:
```
---- electrum_protocol::test::test_blockchain_headers stdout ----
thread 'electrum_protocol::test::test_blockchain_headers' panicked at crates/floresta-electrum/src/electrum_protocol.rs:1221:9:
assertion failed: send_request(batch_req, port).await.is_ok()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
We could fix this with `result.unwrap()` or `result.unwrap_err()`, but it worsens readability. I find it nicer to use these new `assert_ok` and `assert_err` macros. Added a few unit and doc tests for …
=> Debug test data with `assert_ok` and `assert_err`

crates/floresta-chain/src/lib.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/error.rs
Relates to #463
We deny the `clippy::unwrap_used` for non test code, so no unwraps can be reintroduced. Then we use expects if it's infallible and no `Result` is returned. If it's infallible but we can return it's clearer to use `?`.
`verify_script` is refactored to return `Result` with chainstore errors, but other return-database-error refactors are `TODO`.
Finally we were returning `BlockNotPresent` errors in cases where the block is actually present but it's `Orphan` or `InvalidChain`. Created a new error variant for these two cases. It's also used in places where we were using `disk_header.height().unwrap()`.
=> Deny unwraps in `floresta-chain`, handle errors

crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
This is almost a carbon copy of the stale #120 minus comment modifications.
Coinbase transactions from blocks [91_722](https://mempool.space/block/91722) and [91_812](https://mempool.space/block/91812) have identical TXIDs to previous transactions. This PR marks them
as unspendable by checking if any of `del_hashes` matches one of these UTXOs.
=> feat: add BIP30 check

justfile
When running regular `cargo doc --no-deps --open` it might not link correctly the crates or intra-links and there are known problems in rustc 1.74.1 doc generator as it cannot solve naming conflicts between libs and binaries with similar names so thir PR aims at using `nightly`.
The `just` already had a command called `just doc` to generate docs but it did not open and it also ran `just test-doc` as well. 
The purpose of this PR is twofold: simplify the `just doc` to literally just create the documentation and to add a new just recipe called `just open-doc` where it will generate docs for all crates on workspace and open it.
This PR is an improvement suggested for #376 (it was not there originally but will help its development).
I added the flag `--workspace` as well to make sure all …
=> [Fix] Created `just open-doc` command

Cargo.lock, crates/floresta-chain/Cargo.toml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-common/src/lib.rs, florestad/Cargo.toml, florestad/src/florestad.rs, florestad/src/json_rpc/blockchain.rs, florestad/src/json_rpc/control.rs, florestad/src/json_rpc/server.rs
The current chainstore is based on `kv`, but it has a few problems:
- When we flush, we get a huge heap spike
- We are getting a 2 or 3 times overhead on headers
- It gets kinda slow to retrieve headers during IBD if we flush early
This commit introduces a bare-bones, ad-hock store that consists in two parts:
- A open addressing, file backed and memory-mapped hash map to keep the relation block_hash -> block_height
- A flat file that contains block headers serialized, in ascending order
To recover a header, given the block height, we simply use pointer arithmetic inside the flat file. If we need to get from the block hash, use the map first, then find it inside the flat file. This has the advantage of not needing explicit flushes (the os will flush it in fixed intervals), flushes are …
=> floresta-chain: new optimized chainstore

florestad/src/json_rpc/server.rs
A new clippy warning was raised for `cloned-ref-to-slice`. This commit fixes the warning that raise an error during lint-features just recipe.
During a CI job in #465, a new clippy warning was raised, maybe due to `nightly` specs for clippy.
=> Fix clippy warning for load_descriptor in florestad json_rpc server

Cargo.lock, crates/floresta-electrum/Cargo.toml, crates/floresta-electrum/src/electrum_protocol.rs, florestad/Cargo.toml, florestad/src/error.rs, florestad/src/florestad.rs, pyproject.toml, tests/example/electrum-test.py, tests/florestad/ssl-test.py, tests/test_framework/electrum/base.py, uv.lock
This PR bumps tokio-rustls to  26.0. The older version had a security vulnerability and couldn't be compiled to some targets (e.g. RISC-V). This new version fixes all of this.
It also fixes one bug with the ssl test.
=> chore: update tokio-rustls to the latest version

doc/fuzzing.md, fuzz/Cargo.toml, fuzz/fuzz_targets/addrman.rs
This PR adds a fuzz target to cover address manager stuff. It creates a vector of `addrv2` messages that it uses to extract addresses, convert to local addresses and then push to the addrman. Therefore, it explores other functions like `get_addresses_to_send`, `get_address_to_connect` and `rearrange_buckets`.
=> fuzz: add target for addrman

crates/floresta-wire/src/lib.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/node_interface.rs, crates/floresta-wire/src/p2p_wire/running_node.rs
This Changes only add `sync_node` and `chain_selector` to `lib.rs` of `crates/floresta-wire/src/lib.rs` so them can be detected by docs.
it was 
and you can see the difference running `cargo doc --open` in 3aa72032a78ade5ea728546e6fc7c887c0c7b462
=> [Fix] Import sync_node and chain_selector

crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
Previously we were doing:
```rust
unsafe fn get_header_by_hash(
&self,
hash: BlockHash,
) -> Result<Option<DiskBlockHeader>, FlatChainstoreError> {
let header = self
.block_index
.get_index_for_hash(hash, |height| self.get_block_header_by_index(height))?
.map(|height| self.get_block_header_by_index(height)); // DUPLICATED CALL
Ok(header.transpose()?.map(|x| x.header))
}
```
Which we can optimize/simplify by making the `get_index_for_hash` function directly return the header as well, which is free since it's already fetched.
To make this easier I made the `IndexBucket` enum contain the header if occupied (I think this is good as it's data related to the entry we searched for), and named the fields for clarity.
```rust
pub enum IndexBucket {
Empty { ptr: *mut Index },
Occupied {
ptr: *mut …
```
=> Optimize `FlatChainStore` and improve tests

crates/floresta-cli/src/lib.rs, crates/floresta-cli/src/main.rs, crates/floresta-cli/src/parsers.rs, crates/floresta-cli/src/rpc.rs, crates/floresta-cli/src/rpc_types.rs, crates/floresta-electrum/src/electrum_protocol.rs, crates/floresta-watch-only/src/lib.rs, crates/floresta-watch-only/src/merkle.rs, crates/floresta-wire/src/p2p_wire/node.rs, florestad/Cargo.toml, florestad/src/json_rpc/blockchain.rs, florestad/src/json_rpc/res.rs, florestad/src/json_rpc/server.rs
Fix #378
This commit present some changes for gettxoutproof, adding the optional blockhash
input which will make the method interns differ, searching for the transactions
inside the specified block, otherwise, the previous default behavior of getting it
from the wallet cache remains. The method now receives an array of txids instead of
just one.
Also, now named gettxoutproof, was gettxproof.
A unused #[allow(unused)] was also removed from merkle.rs
While trying to fork and just complete #379 to accomplish one of [`0.8.0 milestones`](https://github.com/vinteumorg/Floresta/milestone/3) i noticed some opportunities to optimize some decisions and add two new fixes to the #378 issue. (1. and 2.)
Still validating if the changes are effective and are working.
- Ran `just pcc` (recommended but …
=> [Rpcsaga] add blockhash to gettxoutproof

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
If `florestad` has an unclean shutdown, there's a very specific situation where we may have the `SyncNode` not only stuck, but it's memory usage spiraling out of control. I've got an OOM killing because of this bug (see the second commit for more info). This PR fixes both of them.
Each bug is clearly explained each commit's message. They are so small that I didn't think we need two PRs for them.
=> Bugfix: fix two bugs that may happen after an unclean shutdown

Cargo.lock, crates/floresta-chain/Cargo.toml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, florestad/src/florestad.rs
This commit adds a simple, XOR-based check for integrity for the
flat_chain_store. If we find it to be corrupted, we reindex to find how
much of it is lost, and try to continue from there.
There's no error-correction logic in this commit, because this tends to
bring complexity and require more space. Since modern file-systems are
so good at keeping things from corrupting, I don't think there's that
much need to make our own error correction code here.
Depends on #251
=> flat-chain-store: Detect file corruption and reindex if needed.

crates/floresta-wire/src/p2p_wire/error.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
* Changed the return type of function signature from `Option<()>` to `Result<(), WireError>`;
* adapted the function calls on node.rs, running_node.rs and sync_node.rs;
* added two new types of errors (`NoAddressAvailable` and `AlreadyConnected`) on `WireError`. enum.
While developing #465, it was discussed to change the return type of `create_connection`. This PR follow this discussion.
=> Change create_connection return type on `floresta-wire/src/p2p_wire/node.rs`                

crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-common/src/macros.rs, crates/floresta-watch-only/src/memory_database.rs
Fix some lint warnings and docstring tests that appeared on nightly rust version.
=> Fix lint lifetime warnings and docstring tests

crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, tests/floresta-cli/addnode-test.py
* added `maybe_open_connection_with_added_peers` method to `handle_addnode_add_peer`;
* adjusted `TIMEOUT` on addnode tests.
Previously the `addnode` command implementation followed the procedure of not connect immediately the added node. This PR implements the possibility of connect immediately after adding the node to the `added_peers` list. 
=> [RPC] Implementation detail for addnode: connect to peer after add it

crates/floresta-cli/src/main.rs, crates/floresta-cli/src/rpc.rs, crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/peer.rs, florestad/src/cli.rs, florestad/src/main.rs, tests/floresta-cli/addnode-test.py, tests/test_framework/rpc/bitcoin.py
Closes #416
We already have a good quorum of people running nodes that support v2, we can prefer v2 connections over v1 at this point safely. The only exception for now is `utreexod`, that still doesn't have v2, but we need to connect with them do download proofs.
~This commit adds a logic that turns the v1 fallback off for all non-utreexo peers~
This commit adds a logic that turns the v1 fallback off for all non-utreexo peers, unless the `allow-v1-fallback` CLI option was set to true. We also deny fallback for the `addnode` rpc, iff the `v2transport` option was set.
=> wire: prefer v2 connections for non-utreexo peers

.github/workflows/benchmarks.yml, crates/floresta-chain/Cargo.toml, crates/floresta-chain/benches/chain_state_bench.rs, crates/floresta-chain/src/lib.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, doc/benchmarking.md, florestad/src/florestad.rs, justfile
In _chain_state.rs_ tests we now conditionally compile the `ChainState<FlatChainStore>`.
I am also re-exporting the flat store module conditionally at the root of floresta-chain. In this module I have removed a couple of `pub` keywords and some unused `Index` methods. We now check that the index is only 31 bits before creation, which avoids misusing `update_block_index` with a very big height.
Then at the benchmarks we also bench using the flat store version. Updated docs, recipe and workflow to compile benches with `experimental-db`.
=> Use FlatChainStore in tests and benches

crates/floresta-cli/src/lib.rs, crates/floresta-cli/src/main.rs, florestad/src/json_rpc/control.rs, tests/floresta-cli/stop-test.py
* change return string "florestad stopping" to "Floresta stopping";
* added a docstring for `stop` rpc command compliant with core;
* include bitcoin core to stop test.
The [Bitcoin Core `stop` rpc command](https://bitcoincore.org/en/doc/29.0.0/rpc/control/stop/) return the message `'Bitcoin Core stopping'` and our `stop` message retuns a little different message (`'florestad stopping'`).
=> [RPC] Change the stop return value to be compliant wit Bitcoin Core 

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, tests/florestad/reorg-chain.py, tests/prepare.sh, tests/test_framework/rpc/base.py, tests/test_framework/rpc/utreexo.py
Right now, if we ever encounter ourselves in a reorg of the chain, we will get into a corrupted state, because we won't update our accumulator for the no most-work-chain. Therefore, causing us to get stuck.
This commit adds logic to save an retrieve accumulators from different heights, allowing a full reorg of our chain.
=> chain: handle accumulator reorg

crates/floresta-cli/src/main.rs, florestad/src/json_rpc/control.rs, tests/floresta-cli/addnode-test.py, tests/floresta-cli/getrpcinfo-test.py, tests/test_framework/__init__.py, tests/test_framework/rpc/bitcoin.py
Fix #516
* changes the `get_rpc_info` method to return the
`req.when.elapsed().as_micros() as u64` instead
`req.when.elapsed().as_secs()`;
* added docstring documentation compliant with core for `getrpcinfo` in
`floresta-cli`;
* added `getrpcinfo` method in
`tests/test_framework/rpc/bitcoin.py::BitcoinRPC`;
* added a bitcoind node in
`tests/test_framework/floresta-cli/getrpcinfo-test.py`.
=> [RPC] Fix getrpcinfo to return the duration compliant with core

Cargo.lock, crates/floresta-common/Cargo.toml
`core2` was made unused by #487, but it's still mentioned is floresta-common. This commit removes it
=> remove core2

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/chainstore.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs
I have added a new required method to `ChainStore` that allows fetching the header directly from the height, which is supported out of the box with `FlatChainStore`.
I also made the flat store `Index` impl be under its own module, enforcing we always use the API. Then I refactored `get_block_header_by_index` into the inner `get_disk_header`, which is more concise. This also ensures our heights are checked to be 31-bits.
EDIT: `save_roots_for_block` now returns error if we don't have the respective header, which makes the behavior more consistent. (same for the load function)
=> Simplify flat store, create `get_header_by_height`

florestad/src/json_rpc/server.rs
* This commit fixes the correct ip and port information returned from TcpListener made in #531
Previously, if we passed `--rpc-address=127.0.0.1:0` it didn't log the port choosen by system. Now this log the correct port.
=> Fix action ip:port address for log RPC info

.github/workflows/fuzz.yml, Cargo.toml, contrib/feature_matrix.sh, doc/benchmarking.md, justfile, metrics/Cargo.toml
I added these two packages to the crate list in `feature_matrix` so that we lint them (and test them if in the future we add tests).
The `just lint` recipe already checks them since it is run with the `--workspace` flag (and `just fmt` uses the `--all` flag). This change is to enforce clippy at CI.
I updated the benchmarking docs, and also fixed [an issue](https://github.com/JoseSK999/Floresta/actions/runs/15909410255/job/44872820406#step:8:39) with the `cargo-fuzz` installation.
=> Lint `fuzz` and `metrics`

.github/workflows/fuzz.yml, crates/floresta-chain/src/lib.rs, crates/floresta-compact-filters/src/lib.rs, crates/floresta-electrum/src/lib.rs, crates/floresta-watch-only/src/lib.rs, flake.lock, flake.nix
We need to use the latest nightly for `clippy` in flake.nix, such that it recognizes newer lints that we rely on.
In order to use the latest nightly, I updated the flake.lock `rust-overlay` via:
```bash
nix --experimental-features "nix-command flakes" flake update --update-input rust-overlay
```
This PR builds on top #541 (for cargo-fuzz install) and #543  (which adds the allow `clippy::manual_is_multiple_of`). These allows were required because the new lint suggests using [a method](https://doc.rust-lang.org/stable/std/primitive.u32.html#method.is_multiple_of) that our MSRV doesn't have.
=> Fix nix flakes check

crates/floresta-wire/src/p2p_wire/node.rs, crates/floresta-wire/src/p2p_wire/node_context.rs, crates/floresta-wire/src/p2p_wire/peer.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs, crates/floresta-wire/src/p2p_wire/transport.rs, tests/floresta-cli/addnode-test.py
Fixes #511
This PR makes some minor changes to make sure our `sync_node` works with slow connections. Our banning logic was too agressive for slow connections, we also may lose some blocks and just get stuck. This gives more margin for those peers, make sure we really don't miss any block and remove one case where we would ask for the same block twice.
This PR also renames `Timeout` to `PingTimeout`, since the only case we use it is if the peer didn't respond a `Ping` in time. I'm also adding a log for utreexo block messages (we had it for all messages but this one).
Finally, I'm using a buffered reader to read from wire, as this tends to perform better when our remote connection is slower (we create one big buffer instead of making tons of small syscalls).
=> Wire: small fixes and improvements

crates/floresta-chain/src/pruned_utreexo/consensus.rs, crates/floresta-chain/src/pruned_utreexo/error.rs, crates/floresta-cli/src/lib.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, crates/floresta-wire/src/p2p_wire/sync_node.rs
When trying to reuse the Bitcoin Core tests, one of the problems I found is that we don't implement three basic checks that are performed in Core's checkTransaction (from the consensus directory): https://github.com/bitcoin/bitcoin/blob/master/src/consensus/tx_check.cpp
Transactions must have:
- At least 1 input
- At least 1 output
```c++
// Basic checks that don't depend on any context
if (tx.vin.empty())
return state.Invalid(TxValidationResult::TX_CONSENSUS, "bad-txns-vin-empty");
if (tx.vout.empty())
return state.Invalid(TxValidationResult::TX_CONSENSUS, "bad-txns-vout-empty");
```
- And no null PrevOut if not coinbase
```c++
if (tx.IsCoinBase())
{
if (tx.vin[0].scriptSig.size() < 2 || tx.vin[0].scriptSig.size() > 100)
return state.Invalid(TxValidationResult::TX_CONSENSUS, …
```
=> Add missing `checkTransaction` rules

crates/floresta-chain/benches/chain_state_bench.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs
We have found that the checksum method reads all the virtual data. It may be useful to benchmark it, which helps evaluating future changes. Also the initialization time for each chainstore.
`DbCheckSum` and the method will now be public, although it seems harmless as the inner fields are private (i.e., the only way to produce a `DbCheckSum` is via the method).
=> Benchmark checksums and chainstore creation

crates/floresta-wire/src/p2p_wire/node.rs, tests/florestad/connect-test.py
After https://github.com/vinteumorg/Floresta/pull/501, using --connect with a node that doesn't support V2 would
make the node never make any connections. But --connect should be
allowed to make V1 connections, as it's the only peer allowed to connect
with.
I'm also adding a functional test to make sure it won't happen again.
=> florestad: fix `--connect`

crates/floresta-cli/README.md, crates/floresta-cli/src/main.rs, crates/floresta-cli/src/rpc.rs
Fixes #554
This is the name used in Bitcoin Core. We've renamed the server implementation (due to #453), but didn't change the CLI implementation.
=> cli: rename rescan to rescanblockchain

crates/floresta-electrum/Cargo.toml, crates/floresta-electrum/src/electrum_protocol.rs
If we ran `cargo test` without any features, it might turn both
chainstores on, which causes trouble with our tests, since we have
tests with both chinstore, just overloading the setup functions
at compilation time. Without this change, we get a name clash on
default `cargo run`
It doesn't change anything for the `contrib/test_matrix` script, which
defines features in separate.
=> floresta-chain: fix a test feature problem

crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/running_node.rs
In some circumstances we may have the `PeerNotFound` error being logged over and over again, polluting our logs. This PR fixes this.
=> wire: don't spam the logs with `PeerNotFound`

doc/rpc/template.md
This PR updates the `template.md` file to use the  ```  operator on the json object.
=> Man page cli rendering fix on template.md

florestad/src/florestad.rs
Follow-up of #463;
While review #569, saw that the instantiation of `ElectrumServer` use `expect` method. This commit match a `Result` instead call `expect` so if any error occurs it will be logged with `error!` and `std::process::exit` will be called.
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git commits](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html) and [GitHub's guide to signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)).
=> refactor: get rid of `expect` method of Electrum server

.github/workflows/rust.yml, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-watch-only/src/memory_database.rs, crates/floresta-wire/src/p2p_wire/node.rs, doc/rpc/addnode.md, doc/rpc/template.md, florestad/src/error.rs, florestad/src/json_rpc/blockchain.rs, justfile
I have fixed all doc warnings generated by `cargo +nightly doc ... --document-private-items`, and added a CI and justfile check for it.
`just doc` and `just open-doc` will still only document the public API, but I think it's worth it to also check docstrings on our private items. `just lint` and `just lint-features` will check it now.
=> CI: Check cargo doc lints

tests/floresta-cli/getblockcount.py, tests/test_framework/rpc/bitcoin.py, tests/test_framework/rpc/floresta.py, tests/test_framework/rpc/utreexo.py, tests/test_runner.py
Follow-up https://github.com/vinteumorg/Floresta/issues/453.
Tests the `getblockcount` rpc where we count blocks during a genesis
context and after mining some blocks, comparing the results between
floresta, utreexod and core.
=> test: add a `getblockcount` rpc test

crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, florestad/src/florestad.rs
In `reindex_chain` we don't update the best block field if there's no accumulator associated, but this must be allowed in the chain selection phase (or else we can't "reindex" in that phase).
Another problem is that when we try to shutdown the node during chain selection we don't flush the chain, so we don't save the `BestChain`, which means the next re-start will not identify the chain as initialized and will reindex. But this reindex loops forever because we never update the `BestChain` as explained above.
Also added warns before each `reindex_chain` such that we know the reason in each case.
I am calling the `shutdown` method which in turn calls `flush`. But I am not sure why we see a channel error at the end, perhaps because the peer is already closed:
```bash
[2025-08-04 02:48:46 …
```
=> Fix reindex during chain selection

.github/workflows/rust.yml, CONTRIBUTING.md, contrib/install.sh, contrib/nix/build_floresta.nix, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/flat_chain_store.rs, crates/floresta-chain/src/pruned_utreexo/partial_chain.rs, crates/floresta-cli/src/parsers.rs, crates/floresta-cli/src/rpc_types.rs, crates/floresta-common/src/spsc.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/chain_selector.rs, crates/floresta-wire/src/p2p_wire/mempool.rs, crates/floresta-wire/src/p2p_wire/node_interface.rs, crates/floresta-wire/src/p2p_wire/running_node.rs, doc/nix.md, doc/run.md, florestad/src/florestad.rs, florestad/src/json_rpc/server.rs, justfile, tests/floresta-cli/getblockcount.py, tests/floresta-cli/getmemoryinfo.py, tests/test_framework/__init__.py, tests/test_framework/bitcoin.py, tests/test_framework/daemon/base.py, tests/test_framework/rpc/base.py, tests/test_framework/rpc/floresta.py, typos.toml
Fix #591.
Adding a [`typos` crate](https://github.com/crate-ci/typos), will be possible to check if any typo occurs. While it not fix all possible spell errors, at least mitigate some spelling errors.
=> chore(ci): add spell-check

crates/floresta-chain/src/lib.rs, crates/floresta-chain/src/pruned_utreexo/chain_state.rs, crates/floresta-chain/src/pruned_utreexo/mod.rs, crates/floresta-watch-only/src/lib.rs, crates/floresta/examples/indexer.rs, crates/floresta/examples/node.rs, florestad/src/zmq.rs
Introduces a new subscription mechanism that provides both block data _and_ input UTXO data to subscribers. This enables applications that require knowledge of the spent UTXOs.
- **New trait**: `BlockWithInputsConsumer` for subscribers that need input data alongside blocks
- **New method**: Use `subscribe_with_inputs()` to subscribe to block data with input UTXOs
- **Backward compatible**: Existing `BlockConsumer` subscribers continue to work unchanged
The primary motivation for this PR is to support metaprotocol indexers, which require access to the spent UTXOs of each transaction, but not the full UTXO set. Developers can then integrate Floresta directly into their indexer, so that users do not need to run a separate full node in order to index the chain.
In addition, this PR enables …
=> feat(chain): Enable subscriptions to blocks with input UTXOs

florestad/Cargo.toml
This will fix problem with `dns-lookup` versioning:
https://github.com/vinteumorg/Floresta/issues/611
- I just set to lock the version of `dns-lookup` library to `2.0.4`.
See the `/florestad/Cargo.toml` file and check if bug  https://github.com/vinteumorg/Floresta/issues/611 will be happening.
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git commits](https://withblue.ink/2020/05/17/how-and-why-to-sign-git-commits.html) and [GitHub's guide to signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)).
=> [Fix] Lock lib dns-lookup version to 2.0.4

Cargo.lock, florestad/Cargo.toml, florestad/src/config_file.rs, florestad/src/error.rs, florestad/src/florestad.rs, florestad/src/main.rs, florestad/src/wallet_input.rs
Follow-up of #463;
- Replace `expect` methods in favor of match clause;
- replace `std::proccess::exit` in favor of imported `exit`;
- replace `panic!` calls with `error!` calls followed by `exit(1)`;
- add spaces between `Config` struct propeties to better readability;
- add docstring for `connect` property in the `Config` struct;
- renamed `florestad/src/error.rs::Error` to
`florestad/src/error.rs::FlorestadError`;
- added more types on `florestad/src/error.rs::FlorestadError`.
Finally, you are encouraged to sign all your commits (it proves authorship and guards against tampering—see [How (and why) to sign Git …
=> refactor: remove `expect`, add error handling and lints for `florestad`

florestad/src/json_rpc/mod.rs, florestad/src/json_rpc/request.rs, florestad/src/json_rpc/res.rs, florestad/src/json_rpc/server.rs
Using brackets for getting an item from an array is a bad practice, because if the element isn't there, we will panic. This commit introduces a new way to handle parameters, with actual error handling for missing parameters.
I've also introduced a few helper functions to avoid code duplication.
Finally, I've added a RpcRequest struct to avoid using the black box "Value" type around, which require error handling all the time we access it.
=> RPC: don't use the [] syntax, as it will panic

bin/floresta-cli/src/main.rs, crates/floresta-node/src/florestad.rs, crates/floresta-node/src/json_rpc/res.rs, crates/floresta-node/src/json_rpc/server.rs, crates/floresta-wire/src/p2p_wire/address_man.rs, crates/floresta-wire/src/p2p_wire/node.rs
- Add default `Testnet4` RPC port to RPC server and client.
- Remove catch-all from `get_port`: `Network` is exhaustive since `bitcoin 0.32.7` (https://github.com/rust-bitcoin/rust-bitcoin/pull/4640).
- Remove the `JsonRpcError::InvalidNetwork` variant.
I also left some TODO comments that are to be addressed when https://github.com/rust-bitcoin/rust-bitcoin/pull/4639 gets into a `rust-bitcoin` release. At that point we can remove the `get_port` functions.
=> fix(rpc): add default `Testnet4` RPC port to server and client

doc/README.md, doc/docker.md
fix #577
This commit adds a `docker.md` file to `docs`, describing how to use floresta with docker.
=> doc: add some documentation for docker setup
